export const testProps = () => {
  return {
    userCanWithdrawIssues: false,
    userCanEditIntakeIssues: false,
    userIsVhaAdmin: false,
    userCanRequestIssueUpdates: false,
    userFullName: 'Deborah BvaIntakeAdmin Wise',
    userDisplayName: 'BVADWISE (VACO)',
    userCssId: 'BVADWISE',
    dropdownUrls: [],
    applicationUrls: null,
    buildDate: null,
    taskInProgress: false,
    serverIntake: {
      claimant: '1826209',
      claimantType: 'veteran',
      claimantName: 'Elda Quigley',
      claimantRelationship: 'Veteran',
      benefitType: 'compensation',
      receiptDate: '2024/08/01',
      intakeUser: 'BVADWISE',
      isDtaError: false,
      formType: 'supplemental_claim',
      asyncJobUrl: '/asyncable_jobs/SupplementalClaim/jobs/22',
      hasClearedNonratingEp: false,
      hasClearedRatingEp: false,
      relationships: [],
      contestableIssues: {},
      contestableIssuesByDate: [],
      decisionIssues: [],
      legacyAppeals: [],
      legacyOptInApproved: false,
      payeeCode: null,
      activeNonratingRequestIssues: [],
      pendingIssueModificationRequests: [],
      powerOfAttorneyName: 'Clarence Darrow',
      editIssuesUrl: '/supplemental_claims/ccce635f-711b-41e2-af3f-77374b626296/edit',
      processedAt: '2024-08-05T09:12:42.294-04:00',
      processedInCaseflow: false,
      veteran: {
        fileNumber: '872958715',
        formName: 'King, Anne',
        name: 'Anne King',
        ssn: '658542699'
      },
      veteranInvalidFields: {
        veteranAddressTooLong: false,
        veteranMissingFields: '',
        veteranPayGradeInvalid: false,
        veteranZipCodeInvalid: false
      },
      veteranIsNotClaimant: false,
      veteranValid: true,
      ratings: [],
      requestIssues: [
        {
          id: 292,
          rating_issue_reference_id: null,
          rating_issue_profile_date: null,
          rating_decision_reference_id: null,
          description: 'Other Non-Rated - test issue',
          nonrating_issue_description: 'test issue',
          contention_text: 'Other Non-Rated - test issue',
          approx_decision_date: '2024-08-01',
          category: 'Other Non-Rated',
          notes: null,
          is_unidentified: null,
          ramp_claim_id: null,
          vacols_id: null,
          vacols_sequence_id: null,
          ineligible_reason: null,
          ineligible_due_to_id: null,
          decision_review_title: 'Supplemental Claim',
          title_of_active_review: null,
          contested_decision_issue_id: null,
          withdrawal_date: null,
          contested_issue_description: null,
          end_product_code: '040SCNR',
          end_product_establishment_code: '040SCNR',
          verified_unidentified_issue: null,
          editable: true,
          exam_requested: null,
          vacols_issue: null,
          end_product_cleared: false,
          benefit_type: 'compensation',
          is_predocket_needed: null,
          mst_status: false,
          vbms_mst_status: null,
          pact_status: false,
          vbms_pact_status: null,
          mst_status_update_reason_notes: null,
          pact_status_update_reason_notes: null
        }
      ]
    },
    claimId: 'ccce635f-711b-41e2-af3f-77374b626296',
    featureToggles: {},
    feedbackUrl: '/feedback',
    intakeFromVbms: false
  };
};
