export const ACTIONS = {
  SET_FEATURE_TOGGLES: 'SET_FEATURE_TOGGLES'
  // SET_USER_ROLE: 'SET_USER_ROLE',
  // SET_USER_CSS_ID: 'SET_USER_CSS_ID',
  // SET_USER_ID: 'SET_USER_ID',
  // SET_USER_INFO: 'SET_USER_INFO',
  // SET_FEEDBACK_URL: 'SET_FEEDBACK_URL'
};
