export const ACTIONS = {
  SET_FEATURE_TOGGLES: 'SET_FEATURE_TOGGLES',
  POST_VETERAN_EXTRACT: 'POST_VETERAN_EXTRACT',
  STARTED_VETERAN_EXTRACT: 'STARTED_VETERAN_EXTRACT',
  FAILED_VETERAN_EXTRACT: 'FAILED_VETERAN_EXTRACT'
  // SET_USER_ROLE: 'SET_USER_ROLE',
  // SET_USER_CSS_ID: 'SET_USER_CSS_ID',
  // SET_USER_ID: 'SET_USER_ID',
  // SET_USER_INFO: 'SET_USER_INFO',
  // SET_FEEDBACK_URL: 'SET_FEEDBACK_URL'
};
