export const ACTIONS = {
  ON_RECEIVE_NEW_JUDGE_TEAM: 'ON_RECEIVE_NEW_JUDGE_TEAM',
  ON_RECEIVE_NEW_DVC_TEAM: 'ON_RECEIVE_NEW_DVC_TEAM',
  ON_RECEIVE_NEW_PRIVATE_BAR: 'ON_RECEIVE_NEW_PRIVATE_BAR',
  ON_RECEIVE_NEW_VSO: 'ON_RECEIVE_NEW_VSO',
  ON_RECEIVE_TEAM_LIST: 'ON_RECEIVE_TEAM_LIST'
};
