#! /bin/bash

for testcategory in "$@"; do
    export TEST_CATEGORY="${testcategory}"
    bundle exec rake "spec:parallel:setup:${testcategory}"
    bundle exec rake "spec:parallel:${testcategory}"
done
