#! /usr/bin/env ruby
# parse-log-files
# Reads the JSON returned by the CircleCI artifacts
# endpoint on STDIN, parses log files out of it, and prints
# them to STDOUT.
# For use with capture-log, hopefully located in same dir.
# Usage: curl $circle_artifacts_endpoint | parse-log-files

require "json"

json = ""

ARGF.each_line do |e|
  json += e
end

artifacts = JSON.parse(json)

log_file_urls = artifacts.map do |artifact|
  if artifact["path"] =~ /home\/circleci\/logs\/\d/
    artifact["url"]
  end
end.compact

log_file_urls.sort! { |a, b| a.split("/")[-1] <=> b.split("/")[-1] }

puts log_file_urls
