export const DEPENDENCY_OUTAGE_POLLING_INTERVAL = 30000;
export const LOADING_INDICATOR_COLOR_DISPATCH = '#844E9F';
export const LOADING_INDICATOR_COLOR_CERTIFICATION = '#459fd7';
export const LONGER_THAN_USUAL_TIMEOUT = 10000;
export const CERTIFICATION_DATA_POLLING_INTERVAL = 5000;
export const CERTIFICATION_DATA_OVERALL_TIMEOUT = 180000;
