// poll dependency outage every 2 minutes
export const DEPENDENCY_OUTAGE_POLLING_INTERVAL = 120000;
export const LOADING_INDICATOR_COLOR_CERTIFICATION = '#459FD7';
export const LOADING_INDICATOR_COLOR_DEFAULT = '#323A45';
export const LOADING_INDICATOR_COLOR_HEARINGS = '#68BD07';
export const LONGER_THAN_USUAL_TIMEOUT = 10000;
export const CERTIFICATION_DATA_POLLING_INTERVAL = 5000;
export const CERTIFICATION_DATA_OVERALL_TIMEOUT = 180000;
