version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_patterns:
    - '.codeclimate.yml'
    config:
      strings:
      - TODO
      - FIXME
      - HACK
      - BUG
      - XXX
  grep:
    enabled: true
    config:
      patterns:
        no-disabled-rubocop-rules:
          pattern: rubocop:disable
          annotation: "Don't disable Rubocop rules"
          severity: major
          categories: Complexity
          content: >
            Unless it's a clear false positive, Rubocop rules should not be
            disabled because they allow us to keep our code maintainable. If
            you're not sure how to refactor the code, please reach out to a
            teammate.
  reek:
    enabled: true
    exclude_patterns:
    - 'db/migrate/*'
  rubocop:
    enabled: true
    channel: rubocop-0-64
  scss-lint:
    enabled: true

exclude_patterns:
  - 'db/schema.rb'
  - 'db/seeds.rb'
  - 'node_modules/**/*'
  - 'app/mappers/zip_code_to_lat_lng_mapper.rb'
  - 'tmp/**/*'
  - 'app/assets/**/*'
  - 'spec/**/*'
