# Run overcommit --sign to use file after update

PreCommit:
  # All
  TrailingWhitespace:
    enabled: true
    problem_on_unmodified_line: ignore
  # Ruby/Rails
  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
    command: ['bundle', 'exec', 'rubocop']
  Fasterer:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
    command: ['bundle', 'exec', 'fasterer']