### Generic smell configuration
### Please keep these alphabetical
detectors:
  # You can disable smells completely
  Attribute:
    exclude:
      - BulkTaskAssignment
      - Hearing#override_full_hearing_day_validation
      - PowerOfAttorney
      - QueueConfig
      - RatingDecision
  BooleanParameter:
    exclude:
      - AsyncableJobsReporter#initialize
      - HearingRepository#slot_new_hearing
      - LegacyDocket#distribute_appeals
      - Veteran
  ControlParameter:
    exclude:
      - ExternalApi::VBMSService#self.send_and_log_request
      - Fakes::BGSService
      - HearingRepository#slot_new_hearing
      - LegacyDocket#distribute_appeals
      - Task#actions_allowable?
      - TaskSorter#sort_requires_case_norm?
      - VBMSCaseflowLogger#log
      - Veteran
      - JudgeDecisionReviewTask#additional_available_actions
  UncommunicativeVariableName:
    exclude:
      - Address
      - Fakes::PersistentStore#convert_dates_from
  UncommunicativeMethodName:
    exclude:
      - LegacyAppeal#appellant_address_line_1
      - LegacyAppeal#appellant_address_line_2
  UncommunicativeParameterName:
    exclude:
      - Address
      - Api::V3::DecisionReview::ContestableIssueFinder#initialize
  DataClump:
    exclude:
      - HearingSerializerBase
      - LegacyDocket
      - TaskTreeRenderModule
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    exclude:
      - AMOMetricsReportJob#build_report
      - Api::ApplicationController#on_external_error
      - Api::ApplicationController#upstream_known_error
      - AppealAvailableHearingLocations#suggested_hearing_location
      - AppealTaskHistory#build_events
      - ApplicationRecord#as_hash
      - AssignJudgeteamRoles#process
      - AsyncableJobsReporter
      - ClaimReviewAsyncStatsReporter#as_csv
      - DataIntegrityChecksJob
      - DecisionIssueSyncJob
      - VirtualHearings::DeleteConferencesJob#delete_conference
      - VirtualHearings::DeleteConferencesJob#perform
      - VirtualHearings::DeleteConferencesJob#process_virtual_hearing
      - VirtualHearings::SendEmail#external_message_id
      - Fakes::EndProductStore
      - Fakes::BGSService#get_participant_id_for_user
      - Fakes::BGSServiceRecordMaker
      - Fakes::BGSService#fetch_poas_by_participant_ids
      - Fakes::PersistentStore#convert_dates_from
      - FetchDocumentsForReaderJob#fetch_for_appeal
      - HearingSerializerBase
      - LegacyDocket#count
      - RedistributedCase#legacy_appeal_relevant_tasks
      - LegacyAppeal#cancel_open_caseflow_tasks!
      - MonthlyMetricsReportJob#build_report
      - NightlySyncsJob#sync_vacols_cases
      - RequestIssue#find_or_create_decision_issue_from_rating_issue
      - RequestIssue#special_issues
      - RequestIssueReporter#as_csv
      - SyncReviewsJob
      - TaskTimerJob
      - UpdateCachedAppealsAttributesJob#assignees_for_vacols_id
      - UserReporter#report_user_related_records
      - User#current_case_assignments_with_views
      - User#appeal_has_task_assigned_to_user?
      - VeteranAttributeCacher
      - WarmBgsCachesJob
      - ExternalApi::PexipService#send_pexip_request
  InstanceVariableAssumption:
    exclude:
      - Appeal
      - Task
      - CaseflowJob
      - Api::V3::DecisionReview::HigherLevelReviewIntakeProcessor
      - ETL::Syncer
      - User
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    exclude:
      - Address#initialize
      - ExternalApi::VBMSService#self.create_contentions!
      - LegacyDocket#new_distributed_case
      - Api::V3::DecisionReview::ContestableIssueFinder#initialize
      - QueueRepository#assign_case_to_attorney!
      - VirtualHearings::CreateConferenceJob#perform
  ManualDispatch:
    exclude:
      - Api::V3::DecisionReview::IntakeError#potential_error_code
      - Api::V3::DecisionReview::HigherLevelReviewIntakeParams#attributes?
      - Api::V3::DecisionReview::HigherLevelReviewIntakeParams#params?
      - Api::V3::DecisionReview::IntakeError#error_code
      - Api::V3::DecisionReview::HigherLevelReviewIntakeParams#claimant_object
      - Api::V3::DecisionReview::HigherLevelReviewIntakeParams#claimant_object_present?
      - Api::V3::DecisionReview::HigherLevelReviewIntakeParams#describe_shape_error
  MissingSafeMethod:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
    exclude:
      - AsyncableJobsReporter
  NilCheck:
    enabled: false
  RepeatedConditional:
    exclude:
      - HearingLocation
      - JudgeTeam
      - LegacyAppeal
      - QueueConfig
      - RequestIssue
      - BulkTaskReassignment
      - Task
  TooManyConstants:
    exclude:
      - Fakes::BGSServicePOA
  TooManyInstanceVariables:
    exclude:
      - AmaAppealDispatch
      - DuplicateUserTask
      - LegacyAppealDispatch
      - Address
      - ExternalApi::PexipService
      - InvalidAssigneeStatusOnTaskCreate
      - Api::V3::DecisionReview::ContestableIssueFinder
      - Api::V3::DecisionReview::ContestableIssueParams
      - Api::V3::DecisionReview::IntakeError
  TooManyMethods:
    enabled: false
  TooManyStatements:
    enabled: false
  UtilityFunction:
    public_methods_only: true
    exclude:
      - AddressMapper#get_address_from_veteran_record
      - ClaimReviewAsyncStatsReporter#seconds_to_hms
      - ETL::Builder#last_built
      - ETL::Syncer#filter?
      - ETL::TaskSyncer#filter?
      - Fakes::BGSService
      - Fakes::PexipService
      - HearingAdminActionVerifyAddressTask#available_hearing_admin_actions
      - HearingDispositionChangeJob
      - Helpers::AppealHearingHelper#available_hearing_locations
      - Helpers::AppealHearingHelper#hearings
      - JudgeLegacyDecisionReviewTask#review_action
      - LatestRatingDisabilityEvaluation#latest_disability_evaluation
      - LegacyDocket#age_of_n_oldest_priority_appeals
      - OrganizationOnHoldTasksTab#name
      - OrganizationTrackingTasksTab#column_names
      - PendingIncompleteAndUncancelledTaskTimersQuery#call
      - PowerOfAttorneyMapper#get_claimant_poa_from_bgs_poa
      - Reporter#average
      - Reporter#median
      - Reporter#seconds_to_hms
      - Reporter#percent
      - ScheduleHearingTaskPager#sorted_tasks
      - VBMSCaseflowLogger#log
      - VirtualHearings::ExternalLinkHelper#external_link
      - VirtualHearings::ExternalLinkHelper#phone_link
      - VirtualHearings::VeteranNameHelper#formatted_veteran_name

### Directory specific configuration
# You can configure smells on a per-directory base.
# E.g. the classic Rails case: controllers smell of NestedIterators (see /docs/Nested-Iterators.md) and
# helpers smell of UtilityFunction (see docs/Utility-Function.md)
# Note that we only allow configuration on a directory level, not a file level, so all paths have to point to directories.
directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
  "app/jobs":
    UtilityFunction:
      enabled: false

### Excluding directories
# Directories and files below will not be scanned at all
exclude_paths:
  - db/migrate
  - db/etl/migrate
  - spec
