### Generic smell configuration
### Please keep these alphabetical
detectors:
  # You can disable smells completely
  Attribute:
    exclude:
      - BulkTaskAssignment
      - Hearing#override_full_hearing_day_validation
      - QueueConfig
  BooleanParameter:
    exclude:
      - HearingRepository#slot_new_hearing
  ControlParameter:
    exclude:
      - HearingRepository#slot_new_hearing
  LongParameterList:
    exclude:
      - ExternalApi::VADotGovService#address_validation_request
  UncommunicativeParameterName:
    exclude:
      - ExternalApi::VADotGovService#address_validation_request
  DataClump:
    exclude:
      - HearingSerializerBase
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    exclude:
      - Fakes::EndProductStore
      - FetchDocumentsForReaderJob#fetch_for_appeal
      - AsyncableJobsReporter
      - HearingSerializerBase
      - DataIntegrityChecksJob
      - VeteranAttributeCacher
      - WarmBgsCachesJob
  InstanceVariableAssumption:
    exclude:
      - Appeal
      - Task
  IrresponsibleModule:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NestedIterators:
    exclude:
      - AsyncableJobsReporter
  NilCheck:
    enabled: false
  RepeatedConditional:
    exclude:
      - QueueConfig
  TooManyMethods:
    enabled: false
  TooManyStatements:
    enabled: false
  UtilityFunction:
    public_methods_only: true
    exclude:
      - HearingAdminActionVerifyAddressTask#available_hearing_admin_actions
      - HearingDispositionChangeJob
      - Helpers::AppealHearingHelper#available_hearing_locations
      - Helpers::AppealHearingHelper#hearings

### Directory specific configuration
# You can configure smells on a per-directory base.
# E.g. the classic Rails case: controllers smell of NestedIterators (see /docs/Nested-Iterators.md) and
# helpers smell of UtilityFunction (see docs/Utility-Function.md)
# Note that we only allow configuration on a directory level, not a file level, so all paths have to point to directories.
directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
  "app/jobs":
    UtilityFunction:
      enabled: false

### Excluding directories
# Directories and files below will not be scanned at all
exclude_paths:
  - db/migrate
  - spec
