AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 400

Metrics/AbcSize:
  Max: 30
