imports = []
assignments = []

Dir.glob(File.join(".", "constants", "*")).each do |filepath|
  filename = filepath.split("/").last
  constant_name = filename.split(".").first.upcase

  imports.push("import #{constant_name} from '../../../constants/#{filename}';")
  assignments.push("  #{constant_name}: #{constant_name}")
end

lines_out = [
  "// This file was generated by shared_constants_generator.rb",
  "",
  imports.join("\n"),
  "",
  "const SHARED_CONSTANTS = {",
  assignments.join(",\n"),
  "};",
  "",
  "export default SHARED_CONSTANTS;",
  ""
]

File.write(File.join(".", "client", "app", "constants", "SharedConstants.js"), lines_out.join("\n"))
