/* eslint-disable */
export const tasks = [
  {
    id: '541',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'VacateMotionMailTask',
      label: 'Motion to vacate',
      appeal_id: 10,
      status: 'on_hold',
      assigned_at: '2019-08-16T11:53:06.310-04:00',
      started_at: null,
      created_at: '2019-08-16T11:53:06.310-04:00',
      closed_at: null,
      instructions: ['these are instructions and context'],
      appeal_type: 'Appeal',
      timeline_title: 'VacateMotionMailTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: true,
      hide_from_task_snapshot: true,
      assigned_by: { first_name: 'Mail', last_name: 'member', css_id: 'JOLLY_POSTMAN', pg_id: 57 },
      assigned_to: { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'LitigationSupport', id: 14 },
      assignee_name: 'Litigation Support',
      placed_on_hold_at: '2019-08-16T11:54:11.280-04:00',
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: []
    }
  },
  {
    id: '542',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'VacateMotionMailTask',
      label: 'Motion to vacate',
      appeal_id: 10,
      status: 'assigned',
      assigned_at: '2019-08-16T11:54:11.263-04:00',
      started_at: null,
      created_at: '2019-08-16T11:54:11.263-04:00',
      closed_at: null,
      instructions: ['these are instructions and context'],
      appeal_type: 'Appeal',
      timeline_title: 'VacateMotionMailTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: false,
      hide_from_task_snapshot: false,
      assigned_by: { first_name: 'Litigation', last_name: 'member', css_id: 'LIT_SUPPORT_USER', pg_id: 55 },
      assigned_to: {
        css_id: 'LIT_SUPPORT_USER',
        is_organization: false,
        name: 'LIT_SUPPORT_USER',
        type: 'User',
        id: 55
      },
      assignee_name: 'LIT_SUPPORT_USER',
      placed_on_hold_at: null,
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: [
        {
          label: 'Change task type',
          func: 'change_task_type_data',
          value: 'modal/change_task_type',
          data: {
            options: [
              { value: 'ClearAndUnmistakeableErrorMailTask', label: 'CUE-related' },
              { value: 'AddressChangeMailTask', label: 'Change of address' },
              { value: 'CongressionalInterestMailTask', label: 'Congressional interest' },
              { value: 'ControlledCorrespondenceMailTask', label: 'Controlled correspondence' },
              { value: 'DeathCertificateMailTask', label: 'Death certificate' },
              { value: 'EvidenceOrArgumentMailTask', label: 'Evidence or argument' },
              { value: 'ExtensionRequestMailTask', label: 'Extension request' },
              { value: 'FoiaRequestMailTask', label: 'FOIA request' },
              { value: 'HearingRelatedMailTask', label: 'Hearing-related' },
              { value: 'ReconsiderationMotionMailTask', label: 'Motion for reconsideration' },
              { value: 'AodMotionMailTask', label: 'Motion to Advance on Docket' },
              { value: 'VacateMotionMailTask', label: 'Motion to vacate' },
              { value: 'OtherMotionMailTask', label: 'Other motion' },
              { value: 'PowerOfAttorneyRelatedMailTask', label: 'Power of attorney-related' },
              { value: 'PrivacyActRequestMailTask', label: 'Privacy act request' },
              { value: 'PrivacyComplaintMailTask', label: 'Privacy complaint' },
              { value: 'ReturnedUndeliverableCorrespondenceMailTask', label: 'Returned or undeliverable mail' },
              { value: 'StatusInquiryMailTask', label: 'Status inquiry' },
              { value: 'AppealWithdrawalMailTask', label: 'Withdrawal of appeal' }
            ]
          }
        },
        {
          label: 'Assign to team',
          func: 'assign_to_organization_data',
          value: 'modal/assign_to_team',
          data: {
            selected: null,
            options: [
              { label: 'Board Dispatch', value: 1 },
              { label: 'Case Review', value: 2 },
              { label: 'VLJ Support Staff', value: 4 },
              { label: 'Transcription', value: 5 },
              { label: 'National Cemetery Administration', value: 8 },
              { label: 'Translation', value: 9 },
              { label: 'Quality Review', value: 10 },
              { label: 'Mail', value: 11 },
              { label: 'AOD', value: 12 },
              { label: 'Privacy Team', value: 13 },
              { label: 'Pulac-Cerullo', value: 15 },
              { label: 'Hearings Management', value: 24 },
              { label: 'Hearing Admin', value: 25 }
            ],
            type: 'GenericTask'
          }
        },
        {
          label: 'Re-assign to person',
          func: 'assign_to_user_data',
          value: 'modal/reassign_to_person',
          data: {
            selected: {
              id: 55,
              station_id: '101',
              full_name: 'Litigation Support team member',
              email: null,
              roles: ['LIT_SUPPORT_USER', 'LIT_SUPPORT_USER'],
              last_login_at: '2019-08-19T13:18:21.501-04:00',
              created_at: '2019-07-22T14:15:19.446-04:00',
              css_id: 'LIT_SUPPORT_USER',
              efolder_documents_fetched_at: null,
              selected_regional_office: null,
              updated_at: '2019-08-19T13:18:21.512-04:00',
              display_name: 'LIT_SUPPORT_USER (VACO)'
            },
            options: [],
            type: 'VacateMotionMailTask'
          }
        },
        { label: 'Put task on hold', value: 'modal/place_timed_hold' },
        {
          label: 'Mark task complete',
          func: 'complete_data',
          value: 'modal/mark_task_complete',
          data: { modal_body: 'You can find this case in the completed tab of your queue.' }
        },
        {
          label: 'Cancel task',
          func: 'cancel_task_data',
          value: 'modal/cancel_task',
          data: {
            modal_title: 'Cancel task',
            modal_body: 'Cancelling this task will return it to the assigner',
            message_title: "Task for Bob Smith's case has been cancelled",
            message_detail:
              "If you've made a mistake, please email Litigation Support team member to manage any changes."
          }
        },
        {
          label: 'Notify OGC of Pulac-Cerullo',
          func: 'assign_to_pulac_cerullo_data',
          value: 'modal/assign_to_pulac_cerullo',
          data: {
            selected: { id: 15, name: 'Pulac-Cerullo', participant_id: null, role: null, url: 'pulac-cerullo' },
            options: [{ label: 'Pulac-Cerullo', value: 15 }],
            type: 'PulacCerulloTask'
          }
        }
      ]
    }
  },
  {
    id: '540',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'VacateMotionMailTask',
      label: 'Motion to vacate',
      appeal_id: 10,
      status: 'on_hold',
      assigned_at: '2019-08-16T11:53:06.291-04:00',
      started_at: null,
      created_at: '2019-08-16T11:53:06.291-04:00',
      closed_at: null,
      instructions: [],
      appeal_type: 'Appeal',
      timeline_title: 'VacateMotionMailTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: false,
      hide_from_task_snapshot: false,
      assigned_by: { first_name: '', last_name: '', css_id: null, pg_id: null },
      assigned_to: { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'MailTeam', id: 11 },
      assignee_name: 'Mail',
      placed_on_hold_at: '2019-08-16T11:53:06.325-04:00',
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: []
    }
  },
  {
    id: '29',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'DistributionTask',
      label: 'Distribution Task',
      appeal_id: 10,
      status: 'on_hold',
      assigned_at: '2019-07-22T14:15:17.034-04:00',
      started_at: null,
      created_at: '2019-07-22T14:15:17.034-04:00',
      closed_at: null,
      instructions: [],
      appeal_type: 'Appeal',
      timeline_title: 'DistributionTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: false,
      hide_from_task_snapshot: false,
      assigned_by: { first_name: '', last_name: '', css_id: null, pg_id: null },
      assigned_to: { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'Bva', id: 3 },
      assignee_name: "Board of Veterans' Appeals",
      placed_on_hold_at: '2019-07-22T14:15:17.093-04:00',
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: []
    }
  },
  {
    id: '30',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'EvidenceSubmissionWindowTask',
      label: 'Evidence Submission Window Task',
      appeal_id: 10,
      status: 'assigned',
      assigned_at: '2019-07-22T14:15:17.080-04:00',
      started_at: null,
      created_at: '2019-07-22T14:15:17.080-04:00',
      closed_at: null,
      instructions: [],
      appeal_type: 'Appeal',
      timeline_title: 'EvidenceSubmissionWindowTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: false,
      hide_from_task_snapshot: false,
      assigned_by: { first_name: '', last_name: '', css_id: null, pg_id: null },
      assigned_to: { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'MailTeam', id: 11 },
      assignee_name: 'Mail',
      placed_on_hold_at: null,
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: []
    }
  },
  {
    id: '28',
    type: 'task',
    attributes: {
      is_legacy: false,
      type: 'RootTask',
      label: 'Root Task',
      appeal_id: 10,
      status: 'on_hold',
      assigned_at: '2019-07-22T14:15:16.994-04:00',
      started_at: null,
      created_at: '2019-07-22T14:15:16.994-04:00',
      closed_at: null,
      instructions: [],
      appeal_type: 'Appeal',
      timeline_title: 'RootTask completed',
      hide_from_queue_table_view: false,
      hide_from_case_timeline: true,
      hide_from_task_snapshot: true,
      assigned_by: { first_name: '', last_name: '', css_id: null, pg_id: null },
      assigned_to: { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'Bva', id: 3 },
      assignee_name: "Board of Veterans' Appeals",
      placed_on_hold_at: '2019-07-22T14:15:17.044-04:00',
      on_hold_duration: null,
      docket_name: 'evidence_submission',
      case_type: 'Original',
      docket_number: '190721-10',
      docket_range_date: null,
      veteran_full_name: 'Bob Smith',
      veteran_file_number: '500000009',
      closest_regional_office: null,
      external_appeal_id: '78584fa0-54b5-4ada-b760-f75abc53e19e',
      aod: false,
      issue_count: 0,
      external_hearing_id: null,
      available_hearing_locations: [],
      previous_task: { assigned_at: null },
      document_id: null,
      decision_prepared_by: { first_name: null, last_name: null },
      available_actions: []
    }
  }
];

export const attorneys = [
  { css_id: null, is_organization: true, name: 'LIT_SUPPORT_USER', type: 'Bva', id: 3 },
  {
    id: 68,
    created_at: '2019-07-22T14:15:21.843-04:00',
    css_id: 'BVAEERDMAN',
    efolder_documents_fetched_at: null,
    email: null,
    full_name: 'Ezra M Erdman',
    last_login_at: null,
    roles: [],
    selected_regional_office: null,
    station_id: '101',
    updated_at: '2019-07-29T12:44:21.989-04:00',
    display_name: 'BVAEERDMAN (VACO)'
  },
  {
    id: 69,
    created_at: '2019-07-22T14:15:21.862-04:00',
    css_id: 'BVARDUBUQUE',
    efolder_documents_fetched_at: null,
    email: null,
    full_name: 'Reanna C Du Buque',
    last_login_at: null,
    roles: [],
    selected_regional_office: null,
    station_id: '101',
    updated_at: '2019-07-29T12:44:22.000-04:00',
    display_name: 'BVARDUBUQUE (VACO)'
  },
  {
    id: 70,
    created_at: '2019-07-22T14:15:21.884-04:00',
    css_id: 'BVALSHIELDS',
    efolder_documents_fetched_at: null,
    email: null,
    full_name: 'Lela X Shields',
    last_login_at: null,
    roles: [],
    selected_regional_office: null,
    station_id: '101',
    updated_at: '2019-07-29T12:44:22.012-04:00',
    display_name: 'BVALSHIELDS (VACO)'
  }
];
