DECLARE
	bf_key VARCHAR2(12);
BEGIN
    FOR l_counter IN 1..30
    LOOP
        SELECT VACOLS_DEV.BFKEYSEQ.NEXTVAL INTO bf_key FROM DUAL;
        INSERT INTO VACOLS_DEV.BRIEFF (BFKEY, BFCORKEY, BFCORLID, BFDOCIND, BFCURLOC, BFREGOFF, BFDLOOUT, BFDDEC, BFHR)
            values (bf_key, 'CK285560','123456789S', NULL, '57', 'RO18', current_timestamp, NULL, '2');
        INSERT INTO VACOLS_DEV.FOLDER (TICKNUM,TICORKEY,TISTKEY,TINUM,TIFILOC,TIADDRTO,TITRNUM,TICUKEY,TIDSNT,TIDRECV,TIDDUE,TIDCLS,TIWPPTR,TIWPPTRT,TIADUSER,TIADTIME,TIMDUSER,TIMDTIME,TICLSTME,TIRESP1,TIKEYWRD,TIACTIVE,TISPARE1,TISPARE2,TISPARE3,TIREAD1,TIREAD2,TIMT,TISUBJ1,TISUBJ,TISUBJ2,TISYS,TIAGOR,TIASBT,TIGWUI,TIHEPC,TIAIDS,TIMGAS,TIPTSD,TIRADB,TIRADN,TISARC,TISEXH,TITOBA,TINOSC,TI38US,TINNME,TINWGR,TIPRES,TITRTM,TINOOT,TIOCTIME,TIOCUSER,TIDKTIME,TIDKUSER,TIPULAC,TICERULLO,TIPLNOD,TIPLWAIVER,TIPLEXPRESS,TISNL,TIVBMS,TICLCW) values (bf_key,'CK285560','AHUDSON','5814379','A',null,'944883162S',null,null,to_date('23-JUN-22','DD-MON-RR'),null,null,null,null,'RO46',to_date('16-JUL-14','DD-MON-RR'),'RO49',to_date('28-JAN-22','DD-MON-RR'),null,'RO46','ACTIVE',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Y',null,null,null,null,null,null,null,null,to_date('23-JUN-22','DD-MON-RR'),'SBEAHAN',null,null,null,null,null,null,'Y',null);
        INSERT INTO VACOLS_DEV.ISSUES (ISSKEY,ISSSEQ,ISSPROG,ISSCODE,ISSLEV1,ISSLEV2,ISSDESC)
        values(bf_key, '2', '02', '15', '03', '5260','Maiores nostrum porro qui.');
    END LOOP;
END;
