export const ACTIONS = {
  SET_SELECTING_JUDGE: 'SET_SELECTING_JUDGE',

  PUSH_BREADCRUMB: 'PUSH_BREADCRUMB',
  POP_BREADCRUMB: 'POP_BREADCRUMB',
  RESET_BREADCRUMBS: 'RESET_BREADCRUMBS',

  SET_FOOTER_BUTTONS: 'SET_FOOTER_BUTTONS',

  HIGHLIGHT_INVALID_FORM_ITEMS: 'HIGHLIGHT_INVALID_FORM_ITEMS',
  RESET_ERROR_MESSAGES: 'RESET_ERROR_MESSAGES',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE: 'HIDE_ERROR_MESSAGE',

  REQUEST_SAVE: 'REQUEST_SAVE',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  SAVE_FAILURE: 'SAVE_FAILURE'
};
