export const ACTIONS = {
  SET_SELECTING_JUDGE: 'SET_SELECTING_JUDGE',

  PUSH_BREADCRUMB: 'PUSH_BREADCRUMB',
  POP_BREADCRUMB: 'POP_BREADCRUMB',
  RESET_BREADCRUMBS: 'RESET_BREADCRUMBS',

  HIGHLIGHT_INVALID_FORM_ITEMS: 'HIGHLIGHT_INVALID_FORM_ITEMS',
  RESET_ERROR_MESSAGES: 'RESET_ERROR_MESSAGES',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE: 'HIDE_ERROR_MESSAGE',
  RESET_SUCCESS_MESSAGES: 'RESET_SUCCESS_MESSAGES',
  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  HIDE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',

  REQUEST_SAVE: 'REQUEST_SAVE',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  SAVE_FAILURE: 'SAVE_FAILURE',
  RESET_SAVE_STATE: 'RESET_SAVE_STATE'
};
