export const ACTIONS = {
  SET_FEATURE_TOGGLES: 'SET_FEATURE_TOGGLES',
  SET_SELECTING_JUDGE: 'SET_SELECTING_JUDGE',
  SET_USER_ROLE: 'SET_USER_ROLE',
  SET_USER_CSS_ID: 'SET_USER_CSS_ID',
  SET_USER_ID: 'SET_USER_ID',
  SET_FEEDBACK_URL: 'SET_FEEDBACK_URL',

  SET_TARGET_USER: 'SET_TARGET_USER',

  HIGHLIGHT_INVALID_FORM_ITEMS: 'HIGHLIGHT_INVALID_FORM_ITEMS',
  RESET_ERROR_MESSAGES: 'RESET_ERROR_MESSAGES',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE: 'HIDE_ERROR_MESSAGE',
  RESET_SUCCESS_MESSAGES: 'RESET_SUCCESS_MESSAGES',
  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  HIDE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',

  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  REQUEST_SAVE: 'REQUEST_SAVE',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  SAVE_FAILURE: 'SAVE_FAILURE',
  RESET_SAVE_STATE: 'RESET_SAVE_STATE',

  SET_SELECTED_ASSIGNEE: 'SET_SELECTED_ASSIGNEE',
  SET_SELECTED_ASSIGNEE_SECONDARY: 'SET_SELECTED_ASSIGNEE_SECONDARY',
  RESET_ASSIGNEES: 'RESET_ASSIGNEES',

  TOGGLE_VETERAN_CASE_LIST: 'TOGGLE_VETERAN_CASE_LIST',
  SHOW_VETERAN_CASE_LIST: 'SHOW_VETERAN_CASE_LIST',
  HIDE_VETERAN_CASE_LIST: 'HIDE_VETERAN_CASE_LIST',
  SET_USER_IS_VSO_EMPLOYEE: 'SET_USER_IS_VSO_EMPLOYEE',
  SET_ORGANIZATION_IDS: 'SET_ORGANIZATION_IDS',
  SET_ORGANIZATIONS: 'SET_ORGANIZATIONS',

  SET_CAN_EDIT_AOD: 'SET_CAN_EDIT_AOD',
  SET_CAN_EDIT_NOD_DATE: 'SET_CAN_EDIT_NOD_DATE',
  SET_USER_IS_COB_ADMIN: 'SET_USER_IS_COB_ADMIN',
  SET_CAN_EDIT_CAVC_REMANDS: 'SET_CAN_EDIT_CAVC_REMANDS',
  SET_CAN_VIEW_OVERTIME_STATUS: 'SET_CAN_VIEW_OVERTIME_STATUS',
  SET_ACTIVE_ORGANIZATION: 'SET_ACTIVE_ORGANIZATION',

  SET_HEARING_DAY: 'SET_HEARING_DAY'
};
