export const ACTIONS = {
  SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER: 'SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER',
  CANCEL_TASK_NOT_RELATED_TO_APPEAL: 'CANCEL_TASK_NOT_RELATED_TO_APPEAL',
  CORRESPONDENCE_INFO: 'CORRESPONDENCE_INFO',
  SHOW_ACTIONS_DROP_DOWN: 'SHOW_ACTIONS_DROP_DOWN',
  REMOVE_TASK_NOT_RELATED_TO_APPEAL: 'REMOVE_TASK_NOT_RELATED_TO_APPEAL'
};
