export const ACTIONS = {
  SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER: 'SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER',
  CANCEL_TASK_NOT_RELATED_TO_APPEAL: 'CANCEL_TASK_NOT_RELATED_TO_APPEAL',
  CORRESPONDENCE_INFO: 'CORRESPONDENCE_INFO'
};
