export const ACTIONS = {
  SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER: 'SET_CORRESPONDENCE_TASK_NOT_RELATED_TO_APPEAL_BANNER',
  CORRESPONDENCE_INFO: 'CORRESPONDENCE_INFO',
  CANCEL_TASK_NOT_RELATED_TO_APPEAL: 'CANCEL_TASK_NOT_RELATED_TO_APPEAL',
  TASKS_UNRELATED_TO_APPEAL_EMPTY: 'TASKS_UNRELATED_TO_APPEAL_EMPTY',
  UNRELATED_TASK_LIST: 'UNRELATED_TASK_LIST'
};
