---
openapi: 3.0.2
info:
  title: API V2
  version: V2
servers:
- url: "/api/v2"
paths:
  "/api/v2/appeals":
    get:
      summary: list appeals
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TOKEN
