---
openapi: 3.0.2
info:
  title: API V1
  version: v1
servers:
- url: http://localhost:3000
  description: Local Development server
- url: https://appeals.cf.uat.ds.va.gov
  description: UAT/Staging server
paths:
  "/api/v2/appeals":
    get:
      summary: list appeals
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TOKEN
