---
openapi: 3.0.2
info:
  title: API V2
  version: v2
paths:
  "/api/v2/appeals":
    get:
      summary: list appeals
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
