  CREATE TABLESPACE "AUDITOR" DATAFILE
  '/opt/oracle/oradata/BVAP/auditor.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "BIGROLL" DATAFILE
  '/opt/oracle/oradata/BVAP/bigroll.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "BVA_EMPLOYEE" DATAFILE
  '/opt/oracle/oradata/BVAP/employee.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
   ALTER DATABASE DATAFILE
  '/opt/oracle/oradata/BVAP/employee.dbf' RESIZE 1000000;


  CREATE TABLESPACE "BVA_PHOTO" DATAFILE
  '/opt/oracle/oradata/BVAP/photo.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "DECISION_REV" DATAFILE
  '/opt/oracle/oradata/BVAP/decrev.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "PLATINUM" DATAFILE
  '/opt/oracle/oradata/BVAP/platinum.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ASSIGN" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_assign01.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ASSIGN_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_assign_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ATTACH" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_attach.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ATTACH_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_attach_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ATTYTIME" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_attytime.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_BFCORLID_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_bfcorlid_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_BRIEFF" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_brieff.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_BRIEFF_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_brieff_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_CORRES" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_corres01.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_CORRES_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_corres_ndx1.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_CORRTYPS" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_corrtyps.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_DEATHS" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_death.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_DEATHS_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_death_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_DECASS" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_decass.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_FOLDER" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_folder01.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_FOLDER_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_folder_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_HEARSCHED" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_hearsched.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_INDEXES" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_ISSUES" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_issues.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_OTHDOCS" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_othdocs.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_OTHDOCS_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_othdocs_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_PRIORLOC" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_priorloc01.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_PRIORLOC_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_priorlc_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_RMDREA" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_rmdrea.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_TABLES" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_tables.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_TINUM_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_tinum_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_TITRNUM_NDX" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_titrnum_ndx.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;


  CREATE TABLESPACE "VACOLS_MAIL" DATAFILE
  '/opt/oracle/oradata/BVAP/vcl_mail.dbf' SIZE 1000000
  AUTOEXTEND ON NEXT 8192 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
