module Constants::AttorneyJudgeTeams
  JUDGES = { "BVADAMES" =>
  { judge_name: "Dorilyn Ames",
    attorneys:     [{ name: "Tabatha Blake", css_id: "BVATBLAKE" },
                    { name: "Rochelle Brunot", css_id: "VACOBRUNOR" },
                    { name: "Jerry Fowler", css_id: "VACOFOWLEJ" },
                    { name: "Ryan Frank", css_id: "BVARFRANK" },
                    { name: "Jason Lyons", css_id: "BVAJLYONS" },
                    { name: "Bryan Riordan", css_id: "VACORIORDB" },
                    { name: "Anne Rocktashel", css_id: "BVAAROCK" },
                    { name: "Nadia Stevens", css_id: "VACOSTEVEN" }] },
             "VACOCARACA" =>
  { judge_name: "Angel Caracciolo",
    attorneys:     [{ name: "Laura Crawford", css_id: "VACOCRAWFL" },
                    { name: "Gregory Deemer", css_id: "VACODEEMEG" },
                    { name: "Rahil Gandhi", css_id: "VACOGANDHR" },
                    { name: "Tracy Josephj", css_id: "VACOJOSEPT" },
                    { name: "Meghan Moore", css_id: "BVAMMOORE" },
                    { name: "Jonathan Trickey", css_id: "BVAJTRICKEY" },
                    { name: "Willie Victoria Walker", css_id: "VACOWALKEW" },
                    { name: "Gina Wilkerson", css_id: "BVAGFENICE" }] },
             "BVAKHADDOCK" =>
  { judge_name: "Kristin Haddock",
    attorneys:     [{ name: "Irvin Cannaday", css_id: "BVAICANNADAY" },
                    { name: "Susan Krunic", css_id: "BVASKRUNIC" },
                    { name: "Sonja Mishalanie", css_id: "BVASMISHA" },
                    { name: "Christopher ODonnell", css_id: "VACOODONNC" },
                    { name: "Arooj Sami", css_id: "VACOSAMIA" },
                    { name: "Anne Shawkey", css_id: "BVAASHAWKEY" },
                    { name: "Mariah Sim", css_id: "VACOSIMM" },
                    { name: "Dawn Ware", css_id: "VACOWARED" }] },
             "BVAMDLYON" =>
  { judge_name: "Michael Lyon",
    attorneys:     [{ name: "Philip Franke", css_id: "VACOFRANKP" },
                    { name: "Michael Harris", css_id: "VACOHARRIM30" },
                    { name: "Matthew Miller", css_id: "BVAMMILLER" },
                    { name: "Christopher Murray", css_id: "BVACMURRAY" },
                    { name: "Patricia Olson", css_id: "BVAPOLSON" },
                    { name: "Shana Siesser", css_id: "BVASSIESSER" },
                    { name: "Yuka Taylor", css_id: "VACOTAYLOY" }] },
             "BVAAMAINELLI" =>
  { judge_name: "Anthony Mainelli",
    attorneys:     [{ name: "Heather Harter", css_id: "BVAHJHARTER" },
                    { name: "Chad Howell", css_id: "BVACHOWELL" },
                    { name: "Victoria Narducci", css_id: "VACONARDUV" },
                    { name: "Michael O'Conner", css_id: "VACOOCONNM" },
                    { name: "Chinyere Orie", css_id: "BVACORIE" },
                    { name: "Nasir Rasool", css_id: "VACORASOON" },
                    { name: "Janelle Reid", css_id: "VACOREIDJ" },
                    { name: "Tiakyta Willie", css_id: "BVATWILLIE" }] },
             "VACOSTROMG" =>
  { judge_name: "Gayle Strommen",
    attorneys:     [{ name: "James Acosta-Davis", css_id: "BVAJADAVIS" },
                    { name: "Hallie Brokowsky", css_id: "BVAHBROKOWSKY" },
                    { name: "Christine Grossman", css_id: "VACOGROSSC" },
                    { name: "Kanisha Laffitte", css_id: "VACOLAFFIK" },
                    { name: "Zachary Sahraie", css_id: "VACOSAHRAZ" },
                    { name: "Matthew Schlickenmaier", css_id: "BVAMSCHLICK" },
                    { name: "Amber Smith", css_id: "VACOSMITHA5" },
                    { name: "Katherine Spragins", css_id: "BVAKSPRAGINS" }] },
             "VACOWHITEY" =>
  { judge_name: "Yvette White",
    attorneys:     [{ name: "Dalia Abdelbary", css_id: "VACOABDELD" },
                    { name: "Angela Barner", css_id: "BVAABARNER" },
                    { name: "Tiffany Berry", css_id: "BVATSYKES" },
                    { name: "Cynthia Cho", css_id: "VACOCHOC" },
                    { name: "Agnieszka Lech", css_id: "BVAALECH" },
                    { name: "Gunella Lilly", css_id: "VACOLILLYG" },
                    { name: "Marym Zhuravitsky", css_id: "VACOZHURAM" }] },
             "BVADWIGHT" =>
  { judge_name: "David Wight",
    attorneys:     [{ name: "Ronald Blake", css_id: "VACOBLAKER" },
                    { name: "Erin Miller", css_id: "VACOMILLEE" },
                    { name: "James Nelson", css_id: "VACONELSOJ" },
                    { name: "Michael Nye", css_id: "BVAMNYE" },
                    { name: "Shanthala Raj", css_id: "VACORAJS" },
                    { name: "Paul Rubin", css_id: "BVAPRUBIN" },
                    { name: "Melissa Timbers", css_id: "VACOTIMBEM" },
                    { name: "Robert Watkins", css_id: "BVARWATKINS" }] },
             "BVAJWILLS" =>
  { judge_name: "Jessica Zissimos",
    attorneys:     [{ name: "Damon Chilcote", css_id: "VACOCHILCD1" },
                    { name: "Rebecca Kuczynski", css_id: "VACOKUCZYR" },
                    { name: "Kristyn Osegueda", css_id: "BVAKOSEGUEDA" },
                    { name: "Meredith Postek", css_id: "BVAMPOSTEK" },
                    { name: "Brianne Rideout", css_id: "BVABRIDEOUT" },
                    { name: "Jesmin Saikh", css_id: "BVAJSAIKH" },
                    { name: "Khiedrae Walker", css_id: "VACOWALKEK3" },
                    { name: "Merry Wulff", css_id: "BVAMWULFF" }] },
             "BVAPMLYNCH" =>
  { judge_name: "Paula Dilorenzo",
    attorneys:     [{ name: "Josh Rutkin", css_id: "BVAJRUTKIN" },
                    { name: "Luke McCabe", css_id: "BVALMCCABE" },
                    { name: "Nadia Sangster", css_id: "BVANSANGSTER" },
                    { name: "Megan Purdum", css_id: "BVAMPURDUM" },
                    { name: "Michael Stedman", css_id: "VACOSTEDMM" },
                    { name: "Buck Denton", css_id: "VACODENTOB" },
                    { name: "LaTonja Sinckler", css_id: "VACOSINCKL" },
                    { name: "Sean Mussey", css_id: "VACOMUSSES2" },
                    { name: "Capresha Edwards", css_id: "VACOEDWARC" }] },
             "BVASKENNEDY" =>
  { judge_name: "Susan Kennedy",
    attorneys:     [{ name: "Jacqueline Connolly", css_id: "BVAJCONOLLY" },
                    { name: "Cynthia Wasser", css_id: "BVACWASSER" },
                    { name: "Sarah Richmond", css_id: "BVASBARIAL" },
                    { name: "Saira Spicknall", css_id: "BVASSPICKNALL" },
                    { name: "Marcella Coyne", css_id: "BVAMCOYNE" },
                    { name: "Joshua Costello", css_id: "VACOCOSTEJ1" },
                    { name: "Robert Batten", css_id: "VACOBATTER" },
                    { name: "Nikita Floore", css_id: "VACOFLOORN" },
                    { name: "Gerline Johnson", css_id: "VACOFLEURG" }] },
             "BVANDOAN" =>
  { judge_name: "Nathaniel Doan",
    attorneys:     [{ name: "Ashley Dean", css_id: "BVAADEAN" },
                    { name: "Athena Hemphill", css_id: "BVAAHEMPHILL" },
                    { name: "Sarone Solomon", css_id: "VACOSOLOMS" },
                    { name: "Monica Dermarkar", css_id: "VACODERMAM" },
                    { name: "Kellye Thompson", css_id: "VACOTHOMPK3" },
                    { name: "Yonelle Moore Lee", css_id: "VACOMOOREY" },
                    { name: "Amanda Gibson", css_id: "BVAAGIBSON" },
                    { name: "Courtney Kass", css_id: "VACOKASSC" }] },
             "BVADBROWN" =>
  { judge_name: "Derek Brown",
    attorneys:     [{ name: "Melissa Carsten", css_id: "BVAMCARSTEN" },
                    { name: "Harold Beach", css_id: "BVAHABEACH" },
                    { name: "Mary Rude", css_id: "BVAMRUDE" },
                    { name: "Joseph Montanye", css_id: "VACOMONTAJ" },
                    { name: "Paul Bametzreider", css_id: "VACOBAMETP" },
                    { name: "Tyquili Booker", css_id: "VACOBOOKET" },
                    { name: "Allen Kerpan", css_id: "VACOKERPAA" }] },
             "BVAHROBERT" =>
  { judge_name: "Harvey Roberts",
    attorneys:     [{ name: "John Hutcheson", css_id: "BVAJTHUTCHS" },
                    { name: "Spencer Layton", css_id: "BVASLAYTON" },
                    { name: "Todd Gillett", css_id: "BVATGILLETT" },
                    { name: "Lorelle Driever", css_id: "BVALNOTTLE" },
                    { name: "Kiara Cross", css_id: "VACOCROSSK" },
                    { name: "Hajrah Ahmad", css_id: "VACOAHMADH" },
                    { name: "Thaddeus Cox", css_id: "VACOCOXT2" },
                    { name: "Gillian Flynn", css_id: "VACOFLYNNG" }] },
             "BVAMTENNER" =>
  { judge_name: "Matthew Tenner",
    attorneys:     [{ name: "Shamil Patel", css_id: "BVASPATEL" },
                    { name: "Jessica Smith", css_id: "BVAJESSMITH" },
                    { name: "Yvette Hawkins", css_id: "BVATYHAWKINS" },
                    { name: "Erin Anderson", css_id: "BVAEANDERSON" },
                    { name: "Mark Macek", css_id: "VACOMACEKM" },
                    { name: "Braden Whitelaw", css_id: "VACOWHITEB4" },
                    { name: "Natasha Pendleton", css_id: "VACOPENDLN" },
                    { name: "Vanessa Pratt", css_id: "VACOPRATTV" },
                    { name: "Adrian Jackson", css_id: "BVAADJAKSON" }] },
             "BVAJHWA" =>
  { judge_name: "Jennifer Hwa",
    attorneys:     [{ name: "Jasmine Negron", css_id: "VACONEGROJ" },
                    { name: "Cassie Ford", css_id: "VACOFORDC" },
                    { name: "Kimberly Parke", css_id: "BVAKPARKE" },
                    { name: "Jasmin Freeman", css_id: "VACOFREEMJ2" },
                    { name: "Catherine Cykowski", css_id: "BVACCYKOWSKI" },
                    { name: "Lauren Bush", css_id: "VACOBUSHL2" },
                    { name: "Christopher Casey", css_id: "VACOCASEYC" }] },
             "BVALREIN" =>
  { judge_name: "Lesley Rein",
    attorneys:     [{ name: "Alexis Parrish", css_id: "VACOPARRIA" },
                    { name: "Jornet Shaw", css_id: "BVAJSHAW" },
                    { name: "Melissa Barbee", css_id: "VACOBARBEM2" },
                    { name: "Jill Coogan", css_id: "VACOCOOGAJ" },
                    { name: "Alexandra Dellarco", css_id: "VACODELLAA" },
                    { name: "Shera Finn", css_id: "BVASFINN" },
                    { name: "Carolyn Ryan", css_id: "BVACRYAN" },
                    { name: "Elise Ko", css_id: "VACOKOE" }] },
             "BVAMHAWLEY" =>
  { judge_name: "Milo Hawley",
    attorneys:     [{ name: "Margaret Riley", css_id: "BVAMRILEY" },
                    { name: "Terrence  Griffin", css_id: "BVATGRIFFIN" },
                    { name: "Gillian  Slovick", css_id: "BVAGSLOVICK" },
                    { name: "Brandon Williams", css_id: "BVABWILLIAMS" },
                    { name: "Whitney Ripplinger", css_id: "BVAWRIPP" },
                    { name: "Byron Moore", css_id: "VACOMOOREB1" },
                    { name: "Jonathan  Morris", css_id: "VACOMORRISJ" },
                    { name: "Shawn Ferguson", css_id: "VACOFERGUS1" },
                    { name: "Angela  Norwood", css_id: "VACONORWOA" }] },
             "BVAAMACKEN" =>
  { judge_name: "Andrew Mackenzie",
    attorneys:     [{ name: "Maureen Young", css_id: "BVAMYOUNG" },
                    { name: "Lori Barstow", css_id: "BVALBARSTOW" },
                    { name: "Ann-Lisa Evans", css_id: "BVAALEVANS" },
                    { name: "Jonathan  Abrams", css_id: "BVAJABRAMS" },
                    { name: "Christopher Collins", css_id: "BVACCOLLINS" },
                    { name: "Brian Quarles", css_id: "VACOQUARLB" },
                    { name: "Cameron Mukherjee", css_id: "VACOMUKHEC" },
                    { name: "Christopher Banks", css_id: "VACOBANKSC4" }] },
             "BVAGRSENYK" =>
  { judge_name: "George Senyk",
    attorneys:     [{ name: "James Siegel", css_id: "BVAJRSIEGEL" },
                    { name: "Debbie Breitbeil", css_id: "BVADBREITBEIL" },
                    { name: "Deborah Schechner", css_id: "BVADSCHECH" },
                    { name: "William Skowronski", css_id: "VACOSKOWRW" },
                    { name: "Jason Dupont", css_id: "BVAJDUPONT" },
                    { name: "Nichole Staskowski", css_id: "VACOSTASKN" },
                    { name: "Porschia Poindexter", css_id: "VACOPOINDP" }] },
             "BVAVMOSHI" =>
  { judge_name: "Victoria Moshiashwili",
    attorneys:    [{ name: "Morgan Yuan", css_id: "BVAMYUAN" },
                   { name: "Tereze Matta", css_id: "BVATMATTA" },
                   { name: "Matthew Showalter", css_id: "VACOSHOWAM" },
                   { name: "Nell Robinson", css_id: "VACOROBINN" },
                   { name: "Mary D'Aillard", css_id: "VACODAILLM" }] },
             "BVAMCGRAHAM" =>
  { judge_name: "Caryn Graham",
    attorneys:     [{ name: "Christopher Lawson", css_id: "BVACLAWSON" },
                    { name: "Kshama Hughes", css_id: "BVAKHUGHES" },
                    { name: "Saramae Kreitlow", css_id: "BVASKREITLOW" },
                    { name: "Alex Barone", css_id: "BVAABARONE" },
                    { name: "Tiffany  Wishard", css_id: "BVATWISHARD" },
                    { name: "Bryan Herdliska", css_id: "VACOHERDLB2" },
                    { name: "Thomas Fales", css_id: "VACOFALEST" },
                    { name: "Cynthia Anderson", css_id: "VACOANDERC12" }] },
             "BVAMELARKIN" =>
  { judge_name: "Mary Ellen Larkin",
    attorneys:     [{ name: "Jason Davitian", css_id: "BVAJRDAVIT" },
                    { name: "Robert Burriesci", css_id: "BVARBURRIESCI" },
                    { name: "Jack Komperda", css_id: "BVAJKOMPERDA" },
                    { name: "Caitlin Biggins", css_id: "BVACBIGGINS" },
                    { name: "Eric  Struening", css_id: "BVAESTRUENING" },
                    { name: "Michael Perkins", css_id: "VACOPERKIM5" },
                    { name: "Patrick  McLeod", css_id: "VACOMCLEOP" }] },
             "BVAMSORISIO" =>
  { judge_name: "Mary Sorisio",
    attorneys:     [{ name: "Lori Wells-Green", css_id: "BVALWGREEN" },
                    { name: "Bonnie Yoon", css_id: "BVABYOON" },
                    { name: "Laura Yantz", css_id: "BVALYANTZ" },
                    { name: "Katherine Marenna", css_id: "BVAKWALTERS" },
                    { name: "Lindsay Stallings", css_id: "VACOSTALLL" },
                    { name: "Saurabh Patel", css_id: "VACOPATELS" },
                    { name: "Nicholas Breitbach", css_id: "VACOBREITN" },
                    { name: "Robert Dean", css_id: "VACODEANR2" }] },
             "BVAEVPAREDEZ" =>
  { judge_name: "Estela Velez",
    attorneys:     [{ name: "Karissa Wallin", css_id: "BVAKWALLIN" },
                    { name: "Julie Meawad", css_id: "BVAJMEAWAD" },
                    { name: "Katherine Foster", css_id: "VACOFOSTEK5" },
                    { name: "Jacqueline Sandler", css_id: "VACOSANDLJ" },
                    { name: "Renee Harris", css_id: "VACOHARRIR3" },
                    { name: "Alyssa Arnold", css_id: "VACOARNOLA2" },
                    { name: "Aaron Roe", css_id: "VACOROEA" }] },
             "BVATKONYA" =>
  { judge_name: "Tara Reynolds",
    attorneys:     [{ name: "Sean Pflugner", css_id: "BVASPFLUGNER" },
                    { name: "Nancy Snyder", css_id: "BVANMCELWAIN" },
                    { name: "Alex Hampton", css_id: "BVAAHAMPTON" },
                    { name: "Gordon Fraser", css_id: "BVAGFRASER" },
                    { name: "Alejandro Diaz-Ferguson", css_id: "VACOFERGUA" },
                    { name: "Lisa Nelson", css_id: "VACONELSOL3" },
                    { name: "Ben Winburn", css_id: "VACOWINBUB" },
                    { name: "Carlos Martinez", css_id: "VACOMARTIC9" }] },
             "BVAURPOWELL" =>
  { judge_name: "Ursula Powell",
    attorneys:    [{ name: "Ashley Budd", css_id: "BVAABUDD" },
                   { name: "Anthony Flamini", css_id: "BVAAFLAMINI" },
                   { name: "Jasmine Henriquez", css_id: "BVAJHENRIQUEZ" },
                   { name: "Mikel Espinoza", css_id: "BVAMESPINOZA" },
                   { name: "John H. Baker", css_id: "VACOBAKERJH" }] },
             "BVAMMARTIN" =>
  { judge_name: "Michael Martin",
    attorneys:     [{ name: "Jennifer Deane", css_id: "BVAJDEANE" },
                    { name: "Michelle Katz", css_id: "BVAMPKATZ" },
                    { name: "Timothy Anthony", css_id: "BVATANTHONY" },
                    { name: "Jessica OConnell", css_id: "BVAJOCONNELL" },
                    { name: "Alexandra Solomon", css_id: "BVAASOLOMON" },
                    { name: "Samantha  Mountford", css_id: "VACOMOUNTS" },
                    { name: "Saudiee Brown", css_id: "VACOBROWNS" },
                    { name: "Jeffrey Higgins", css_id: "VACOHIGGIJ" }] },
             "BVALJENG" =>
  { judge_name: "Lana Jeng",
    attorneys:     [{ name: "Amanda Alderman", css_id: "BVAAALDERMAN" },
                    { name: "Miyoung In", css_id: "BVAMJIN" },
                    { name: "Dan Schechter", css_id: "BVADSCHECHT" },
                    { name: "Grace Raftery", css_id: "VACORAFTEG" },
                    { name: "Neferteria Brown", css_id: "VACOBROWNN6" },
                    { name: "Leanne Innet", css_id: "VACOINNETL" },
                    { name: "Stephen Freeman", css_id: "VACOFREEMS" }] },
             "BVABMULLINS" =>
  { judge_name: "Bobby Mullins",
    attorneys:     [{ name: "Sara Schinnerer", css_id: "BVASCHINNERER" },
                    { name: "Patricia Veresink", css_id: "BVAPVERESINK" },
                    { name: "Amber Nolley", css_id: "BVAANOLLEY" },
                    { name: "Alex Kutrolli", css_id: "VACOKUTROA" },
                    { name: "Hannah Fisher", css_id: "VACOFISHEH" },
                    { name: "Nakiya Whitaker", css_id: "VACOWHITAN" },
                    { name: "Renee Trotter", css_id: "VACOTROTTR" },
                    { name: "Timothy King", css_id: "VACOKINGT10" }] },
             "BVALHOWELL" =>
  { judge_name: "Linda Howell",
    attorneys:     [{ name: "Kristina Schaefer", css_id: "BVAKSCHAEFER" },
                    { name: "Kate Kovarovic", css_id: "BVAKKOVAROVIC" },
                    { name: "Mirham Yacoub", css_id: "VACOYACOUM" },
                    { name: "Alex Spigelman", css_id: "VACOSPIGEA" },
                    { name: "Tanga Bernal", css_id: "VACOBERNAT" },
                    { name: "Brendan Evans", css_id: "VACOEVANSB" }] },
             "BVAKBANFIELD" =>
  { judge_name: "Kathy Banfield",
    attorneys:     [{ name: "Daniela Van Wambeke", css_id: "BVADCAMILLERI" },
                    { name: "William  Yates", css_id: "BVAWMYATES" },
                    { name: "Caroline Banister", css_id: "BVACBANISTER" },
                    { name: "Sara Medina", css_id: "VACOMEDINS" },
                    { name: "Rachel Mamis", css_id: "VACOMAMISR" },
                    { name: "Mary Birder", css_id: "VACOBIRDEM" }] },
             "BVANKROES" =>
  { judge_name: "Nathan Kroes",
    attorneys:     [{ name: "Carrie Boyd", css_id: "BVACBOYD" },
                    { name: "David Havelka", css_id: "BVADHAVELKA" },
                    { name: "Russell Veldenz", css_id: "BVARVELDENZ" },
                    { name: "Ellen Brandau", css_id: "BVAEBRANDAU" },
                    { name: "McKayle Bruce", css_id: "BVAMBRUCE" },
                    { name: "Adrian Odya-Weis", css_id: "BVAAWEIS" },
                    { name: "Michael Gonzalez", css_id: "VACOGONZAM6" },
                    { name: "Robert Scarduzio", css_id: "VACOSCARDR" }] },
             "BVAVCLEMENT" =>
  { judge_name: "Vito Clementi",
    attorneys:     [{ name: "Shazia Anwar", css_id: "VACOANWARS2" },
                    { name: "Boris Cohen", css_id: "VACOCOHENB" },
                    { name: "Carolyn Colley", css_id: "VACOCOLLEC" },
                    { name: "Graig Jackson", css_id: "BVAGJACKSON" },
                    { name: "Jacqueline Miller", css_id: "BVAJMILLER" },
                    { name: "Nykeia Miller", css_id: "VACOMILLEN2" },
                    { name: "Joshua Wozniak", css_id: "VACOWOZNIJ" }] },
             "BVAMLKANE" =>
  { judge_name: "Michelle Kane",
    attorneys:     [{ name: "Rachel Costello", css_id: "BVARCOSTELLO" },
                    { name: "Lindsay Durham", css_id: "BVALMOLLAN" },
                    { name: "Mathew Galante", css_id: "VACOGALANM" },
                    { name: "Kerry Hubers", css_id: "BVAKHUBERS" },
                    { name: "Robin Janofsky", css_id: "VACOJANOFR" },
                    { name: "Morgan Lavan", css_id: "BVAMLAVAN" },
                    { name: "James Leamon", css_id: "VACOLEAMOJ" },
                    { name: "Amelia Parsons", css_id: "VACOPARSOA" }] },
             "BVAJBKRAMER" =>
  { judge_name: "Jonathan Kramer",
    attorneys:     [{ name: "Lloyd Cramp", css_id: "BVALMCRAMP" },
                    { name: "Erika Duthely", css_id: "VACODUTHEE" },
                    { name: "Andrew Mack", css_id: "BVAAMACK" },
                    { name: "Johnny Ragheb", css_id: "BVAJRAGHEB" },
                    { name: "Sean Raymond", css_id: "VACORAYMOS" },
                    { name: "Michael Schnibben", css_id: "VACOSCHNIM" },
                    { name: "Tricia Sherrard", css_id: "BVATSHERR" }] },
             "BVASBELCHER" =>
  { judge_name: "Simone Belcher-Mays",
    attorneys:     [{ name: "Romina Casadei", css_id: "BVARCASADEI" },
                    { name: "Bradley Farrell", css_id: "VACOFARREB2" },
                    { name: "Tristin Harper", css_id: "VACOHARPET" },
                    { name: "Jane Lee", css_id: "BVAJLEE" },
                    { name: "Lorryn Logan", css_id: "VACOLOGANL1" },
                    { name: "Jane Nichols", css_id: "BVAJNICHOLS" },
                    { name: "Megan Thomas", css_id: "BVAMTHOMAS" },
                    { name: "Achiya Yaffe", css_id: "VACOYAFFEA" }] },
             "BVAKPARAKAL" =>
  { judge_name: "Kalpana Parakkal",
    attorneys:     [{ name: "Freda Carmack", css_id: "VACOCARMAF" },
                    { name: "Patrick Johnson", css_id: "BVAPJOHNS" },
                    { name: "Thomas Kelly", css_id: "BVATSKELLY" },
                    { name: "Christine Kung", css_id: "BVACKUNG" },
                    { name: "Kirsten Kunz", css_id: "BVAKKUNZ" },
                    { name: "Stephanie Owen", css_id: "VACOOWENSS" },
                    { name: "Renee Williams", css_id: "BVARFWILLIAMS" },
                    { name: "Marla Woodarek", css_id: "VACOWOODAM" }] },
             "BVAJPARKER" =>
  { judge_name: "Jeff Parker",
    attorneys:     [{ name: "Amanda Bedford", css_id: "VACOBEDFOA" },
                    { name: "Eric Blowers", css_id: "BVAEBLOWERS" },
                    { name: "Eva Choi", css_id: "VACOCHOIE1" },
                    { name: "Carla Ferguson", css_id: "BVACPALMER" },
                    { name: "Patrick Meehan", css_id: "VACOMEEHAP" },
                    { name: "Shanna Moore", css_id: "VACOMOORES" },
                    { name: "Ashleigh Tenney", css_id: "BVAATENNEY" }] },
             "BVAHSEESEL" =>
  { judge_name: "Holly Seesel",
    attorneys:     [{ name: "Alan Boal", css_id: "VACOBOALA" },
                    { name: "Amanda Christensen", css_id: "BVAACHRIST" },
                    { name: "Ryan Connally", css_id: "BVARCONNALLY" },
                    { name: "Thomas Jones", css_id: "BVATHJONES" },
                    { name: "Edward Jones", css_id: "VACOJONESE20" },
                    { name: "Naree Nelson", css_id: "BVANNELSON" },
                    { name: "Charles Teague", css_id: "VACOTEAGUC3" }] },
             "BVAAPSIMPSON" =>
  { judge_name: "Alexandra Simpson",
    attorneys:     [{ name: "Dominic Cheng", css_id: "VACOCHENGD" },
                    { name: "Anel Hodzic", css_id: "BVAAHODZIC" },
                    { name: "Rahat Husain", css_id: "VACOHUSAIR" },
                    { name: "Chad Johnson", css_id: "BVADCJOHNSON" },
                    { name: "Alyssa Keninger", css_id: "VACOKENINA" },
                    { name: "Earlene Rosenberg Morgan", css_id: "VACOROSENE" },
                    { name: "Jazamine Stallings", css_id: "VACOSTALLIJ" },
                    { name: "Lynne Yasui", css_id: "BVALYASUI" }] },
             "BVAAJAEGER" =>
  { judge_name: "Anne Jaeger",
    attorneys:     [{ name: "Brennae Brooks", css_id: "VACOBROOKB4" },
                    { name: "Michelle Celli", css_id: "BVAMOLSON" },
                    { name: "Kiara Clark", css_id: "VACOCLARKK1" },
                    { name: "Jonathan Estes", css_id: "VACOESTESJ" },
                    { name: "Lynn Htun", css_id: "VACOHTUNL" },
                    { name: "Alexander Panio", css_id: "BVAAPANIO" },
                    { name: "Kate Sosna", css_id: "BVAKSOSNA" },
                    { name: "Koria Stanton", css_id: "VACOSTANTK" }] },
             "BVADJOHNSON" =>
  { judge_name: "Dana Johnson",
    attorneys:     [{ name: "Daniel Barrett", css_id: "VACOBARRED" },
                    { name: "Michael Mazzucchelli", css_id: "BVAMGMAZUCH" },
                    { name: "Mike Sobiecki", css_id: "BVAMSOBIECKI" },
                    { name: "Mary Tang", css_id: "VACOTANGM" },
                    { name: "Anthony Vieux", css_id: "BVAAVIEUX" },
                    { name: "Kanha Vuong", css_id: "VACOVUONGK" },
                    { name: "Timothy Campbell", css_id: "VACOCAMPB7" },
                    { name: "Erin Mortimer", css_id: "VACOMORTIE" }] },
             "BVAJCROWLEY" =>
  { judge_name: "John Crowley",
    attorneys:     [{ name: "Tatiana Azizi-Barcelo", css_id: "BVAATATIANA" },
                    { name: "Barry Gabay", css_id: "VACOGABAYB" },
                    { name: "Richard Kettler", css_id: "VACOKETTLR" },
                    { name: "Michael Marcum", css_id: "BVAMMARCUM" },
                    { name: "April Snoparsky", css_id: "VACOSNOPAA" },
                    { name: "Sadia Sorathia", css_id: "BVASSORATHIA" },
                    { name: "Neil Werner", css_id: "BVANWERNER" },
                    { name: "Victor Woehlke", css_id: "VACOWOEHLV" }] },
             "BVAMJSKALT" =>
  { judge_name: "Michael Skaltsounis",
    attorneys:     [{ name: "Daniel Bassett", css_id: "BVADBASSETT" },
                    { name: "Brian Cannon", css_id: "VACOCANNOB" },
                    { name: "Scott Dale", css_id: "BVASDALE" },
                    { name: "Anwar Daniels", css_id: "VACODANIEA2" },
                    { name: "Pamela Daugherty", css_id: "VACODAUGHP" },
                    { name: "Jose Carlos Garcia", css_id: "VACOGARCIAJ" },
                    { name: "Michael Rescan", css_id: "VACORESCAM" },
                    { name: "Scott Shoreman", css_id: "BVASSHOREMAN" }] },
             "BVARKESSEL" =>
  { judge_name: "Ryan Kessel",
    attorneys:     [{ name: "Corey Bosely", css_id: "BVACBOSELY" },
                    { name: "Phyllis Childers", css_id: "BVAPCHILDERS" },
                    { name: "Jason George", css_id: "VACOGEORGEJ" },
                    { name: "Brandon Isaacs", css_id: "BVABISAACS" },
                    { name: "David Jimerfield", css_id: "VACOJIMERD" },
                    { name: "Dominic Jones", css_id: "BVADJJONES" },
                    { name: "Armando Santiago", css_id: "BVAASANTIAGO" },
                    { name: "Melanie Taylor", css_id: "BVAMTAYLOR" }] },
             "BVASKREMBS" =>
  { judge_name: "Simone Krembs",
    attorneys:     [{ name: "Ian Altendorfer", css_id: "VACOALTENI" },
                    { name: "Matilda Bilstein", css_id: "VACOBILSTM" },
                    { name: "Aileen Fagan", css_id: "BVAAFAGAN" },
                    { name: "Nathaniel Pettine", css_id: "VACOPETTIN" },
                    { name: "Jennifer Smith-Jennings", css_id: "VACOSMITHJ5" },
                    { name: "Laura Stepanick", css_id: "BVALSTEPANICK" },
                    { name: "Philip Timerman", css_id: "VACOTIMMEP" }] },
             "BVASBUSH" =>
  { judge_name: "Sonnet Bush",
    attorneys:     [{ name: "Ruby Asante", css_id: "VACOASANTR" },
                    { name: "Jennifer Ivey-Crickenberger", css_id: "BVAJLIVEY" },
                    { name: "Elana Lederman", css_id: "VACOLEDERE" },
                    { name: "Sarah Mahoney", css_id: "VACOMAHONS" },
                    { name: "Jarrette Marley", css_id: "BVAJMARLEY" },
                    { name: "Nicole Northcutt", css_id: "BVANNORTHCUTT" },
                    { name: "Katherine Forde", css_id: "BVAKQUANDER" }] },
             "BVASDREISS" =>
  { judge_name: "Steve Reiss",
    attorneys:     [{ name: "Joshua Castillo", css_id: "BVAJCASTILLO" },
                    { name: "Kenneth Ciardiello", css_id: "VACOCIARDK" },
                    { name: "Jacqueline Jordan", css_id: "VACOJORDANJ" },
                    { name: "John Kitlas", css_id: "BVAJKITLAS" },
                    { name: "Scott Regan", css_id: "BVASREGAN" },
                    { name: "Cheryl Samuelson", css_id: "BVACSAMUELSON" },
                    { name: "Tracie Wesner", css_id: "BVATWESNER" },
                    { name: "Michele-Ann Wilson", css_id: "BVAMAWILSON" },
                    { name: "Krzysztof Wysokinski", css_id: "VACOWYSOKK" }] },
             "BVAMBLACK" =>
  { judge_name: "Matthew Blackwelder",
    attorneys:     [{ name: "Tim Berryman", css_id: "BVATBERRYMAN" },
                    { name: "Claire Davidoski", css_id: "VACODAVIDC" },
                    { name: "Stephen Eckerman", css_id: "BVASECKERMA" },
                    { name: "Michelle Franklin", css_id: "VACOFRANKM2" },
                    { name: "Rashida Sims", css_id: "VACOSIMSR" },
                    { name: "Nicole Yeh", css_id: "VACOYEHN" }] },
             "BVABBCOPELD" => { judge_name: "Barbara Copeland",
                                attorneys:     [{ name: "Jasmine Crawford", css_id: "VACOCRAWFJ2" },
                                                { name: "Jake Dworkin", css_id: "BVAJDWORKIN" },
                                                { name: "David Seaton", css_id: "BVADSEATON" },
                                                { name: "Steve Wainaina", css_id: "VACOWAINAS" }] },
             "BVACFLEMING" =>
  { judge_name: "Caroline Fleming",
    attorneys:     [{ name: "Georgio Comninos", css_id: "VACOCOMNIG" },
                    { name: "Lindsey Connor", css_id: "BVALCONNOR" },
                    { name: "Tenisha Jiggets", css_id: "VACOJIGGET" },
                    { name: "David Katz", css_id: "VACOKATZD3" },
                    { name: "Michael Neal", css_id: "VACONEALM" },
                    { name: "Melanie Thompson", css_id: "VACOTHOMPM6" }] },
             "BVASHENEKS" =>
  { judge_name: "Stacey Heneks",
    attorneys:     [{ name: "Debra Bredehorst", css_id: "BVADBREDEHORS" },
                    { name: "Dan Brook", css_id: "BVADBROOK" },
                    { name: "Nadia Kamal", css_id: "BVANKAMAL" },
                    { name: "Elizabeth Kunju", css_id: "VACOKUNJUE" },
                    { name: "Chris Lamb", css_id: "BVACLAMB" },
                    { name: "Pa Noh", css_id: "VACONOHP" },
                    { name: "Alicia Wimbush", css_id: "VACOWIMBIA" }] },
             "BVAMHERMAN" =>
  { judge_name: "Michael Herman",
    attorneys:     [{ name: "Mohammad Alhinnawi", css_id: "VACOALHINM" },
                    { name: "Jennifer Burroughs", css_id: "BVAJBURRO" },
                    { name: "Thomas Douglas", css_id: "BVATDOUGLAS" },
                    { name: "Teresa Grzeczkowicz", css_id: "VACOGRZECT" },
                    { name: "Doug Humphrey", css_id: "VACOHUMPHD" },
                    { name: "Miranda Lee", css_id: "VACOLEEM2" },
                    { name: "Motrya Mac", css_id: "BVAMMAC" },
                    { name: "Elizabeth Rekowski", css_id: "VACOREKOWE" },
                    { name: "Paul Saindon", css_id: "VACOSAINDP" }] },
             "BVAAISHIZ" =>
  { judge_name: "Amy Ishizawar",
    attorneys:     [{ name: "Janet Alexander", css_id: "VACOALEXAJ10" },
                    { name: "Denise Casula", css_id: "BVADMCASULA" },
                    { name: "Kate Churchwell", css_id: "BVAKCHURCH" },
                    { name: "Kathleen Fletcher", css_id: "BVAKFLETCHER" },
                    { name: "Joseph Gervasio", css_id: "BVAJPGERVAS" },
                    { name: "Steve Johnston", css_id: "VACOJOHNSS3" },
                    { name: "Paul Metzner", css_id: "VACOMETZNP" },
                    { name: "Naria Shah", css_id: "VACOSHAHN1" }] },
             "BVAKMILLIKAN" =>
  { judge_name: "Kerri Millikan",
    attorneys:     [{ name: "Cherrelle Bruton", css_id: "VACOBRUTOC" },
                    { name: "Steve Ginski", css_id: "BVASGINSKI" },
                    { name: "Carole Kammel", css_id: "BVACKAMMEL" },
                    { name: "David Nelson", css_id: "BVADSNELSON" },
                    { name: "Pauline Nguyen", css_id: "VACONGUYEP" },
                    { name: "Cheri Smith", css_id: "BVACSMITH" },
                    { name: "Hannah Yoo", css_id: "BVAHYOO" }] },
             "BVATOSHAY" =>
  { judge_name: "Thomas O Shay",
    attorneys:     [{ name: "Sheena Becker", css_id: "BVASFLOT" },
                    { name: "Jeana Bryant", css_id: "BVAJRBRYANT" },
                    { name: "Jenny Cheng", css_id: "BVAJCHENG" },
                    { name: "Jennifer Flynn", css_id: "BVAJFLYNN" },
                    { name: "Saif Kalolwala", css_id: "VACOKALOLS" },
                    { name: "Carolyn Krasinski", css_id: "BVACLKRAS" },
                    { name: "Kimberly Mitchell", css_id: "BVAKMITCHELL" },
                    { name: "Neely Peden", css_id: "VACOPEDENN" }] } }.freeze
  # rubocop:enable Metrics/LineLength
end
