#:nocov:
module Constants::RampJudges
  USERS = {
    preprod: %w[],
    uat: %w[],
    test: %w[],
    development: %w[BVAAABSHIRE BVAOFRANECKI BVAJWEHNER],
    # rubocop:disable Metrics/LineLength
    prod: %w[BVAJHWA BVABKNOPE BVAGWASIK BVAKBCONNER BVALHOWELL VACOWHITEY BVACFLEMING BVABMULLINS BVAKALIBRAN BVAVCHIAPP BVAAISHIZ BVASBELCHER VACOCARACA BVADJOHNSON BVAEVPAREDEZ BVALREIN BVADAMES BVAKHADDOCK BVAMDLYON BVAAMAINELLI VACOSTROMG BVADWIGHT BVAJWILLS BVADBROWN BVAPMLYNCH BVASKENNEDY BVANDOAN BVAHROBERT BVAMTENNER BVAMHAWLEY BVAAMACKEN BVAGRSENYK BVAVMOSHI BVAMCGRAHAM BVAMELARKIN BVAMSORISIO BVATKONYA BVAURPOWELL BVAMMARTIN BVALJENG BVAKBANFIELD BVANKROES BVAVCLEMENT BVAMLKANE BVAJBKRAMER BVAKPARAKAL BVAJPARKER BVAHSEESEL BVAAPSIMPSON BVAAJAEGER BVAJCROWLEY BVAMJSKALT BVARKESSEL BVASKREMBS BVASBUSH BVASDREISS BVASHENEKS BVAMBLACK BVABBCOPELD BVAMHERMAN BVAKKORDICH BVAKMILLIKAN BVATOSHAY BVADWSINGLE BVAHWALKER BVALBARNARD BVAMAUER BVAMKILCOYN BVARFEINBERG BVATASMITH BVAHSCHARTZ BVAJFRANCIS BVADHACHEY BVAMLANE BVAMAPAPPAS BVAKGUNN BVAESLEBOFF BVAPSORISIO BVAJHAGER BVAJMONROE BVAJREINHART BVAMHYLAND]
    # rubocop:enable Metrics/LineLength
  }.freeze
end
#:nocov:
