#:nocov:
module Constants::RampJudges
  USERS = {
    preprod: %w[],
    uat: %w[],
    test: %w[],
    development: %w[BVAAABSHIRE BVAOFRANECKI BVAJWEHNER],
    prod: %w[BVAJHWA BVABKNOPE BVAGWASIK BVAKBCONNER BVALHOWELL VACOWHITEY BVACFLEMING BVABMULLINS BVAKALIBRAN BVAVCHIAPP BVAAISHIZ BVASBELCHER VACOCARACA BVADJOHNSON BVAEVPAREDEZ BVALREIN]
  }.freeze
end
#:nocov:
