#:nocov:
module Constants::RampJudges
  USERS = {
    preprod: %w[],
    uat: %w[],
    test: %w[],
    development: %w[BVAAABSHIRE BVAOFRANECKI BVAJWEHNER],
    # rubocop:disable Metrics/LineLength
    prod: %w[BVADAMES VACOCARACA BVAKHADDOCK BVAMDLYON BVAAMAINELLI VACOSTROMG VACOWHITEY BVADWIGHT BVAJWILLS BVADBROWN BVAPMLYNCH BVASKENNEDY BVANDOAN BVAHROBERT BVAMTENNER BVAJHWA BVALREIN BVAMHAWLEY BVAAMACKEN BVAGRSENYK BVAVMOSHI BVAMCGRAHAM BVAMELARKIN BVAMSORISIO BVAEVPAREDEZ BVATKONYA BVAURPOWELL BVAMMARTIN BVALJENG BVABMULLINS BVALHOWELL BVAKBANFIELD BVANKROES BVAVCLEMENT BVAMLKANE BVAJBKRAMER BVASBELCHER BVAKPARAKAL BVAJPARKER BVAHSEESEL BVAAPSIMPSON BVAAJAEGER BVADJOHNSON BVAJCROWLEY BVAMJSKALT BVARKESSEL BVASKREMBS BVASBUSH BVASDREISS BVASHENEKS BVAMBLACK BVABBCOPELD BVACFLEMING BVAMHERMAN BVAAISHIZ BVAKKORDICH BVAKMILLIKAN BVATOSHAY BVADWSINGLE BVAHWALKER BVALBARNARD BVAMAUER BVAMKILCOYN BVARFEINBERG BVATASMITH BVAVCHIAPP BVAHSCHARTZ BVAJFRANCIS BVADHACHEY BVAMLANE BVAKALIBRAN BVAMAPAPPAS BVAKGUNN BVAGWASIK BVAESLEBOFF BVAPSORISIO BVAJHAGER BVAJMONROE BVAJREINHART BVAMHYLAND BVABKNOPE BVAKBCONNER]
    # rubocop:enable Metrics/LineLength
  }.freeze
end
#:nocov:
