export const ACTIONS = {
  LOAD_CORRESPONDENCES: 'LOAD_CORRESPONDENCES',
  LOAD_VET_CORRESPONDENCE: 'LOAD_VET_CORRESPONDENCE',
  UPDATE_RADIO_VALUE: 'UPDATE_RADIO_VALUE',
  SAVE_CHECKBOX_STATE: 'SAVE_CHECKBOX_STATE',
  CLEAR_CHECKBOX_STATE: 'CLEAR_CHECKBOX_STATE',
  SAVE_APPEAL_CHECKBOX_STATE: 'SAVE_APPEAL_CHECKBOX_STATE',
  CLEAR_APPEAL_CHECKBOX_STATE: 'CLEAR_APPEAL_CHECKBOX_STATE',
  SET_UNRELATED_TASKS: 'SET_UNRELATED_TASKS',
  SET_FETCHED_APPEALS: 'SET_FETCHED_APPEALS'
};
