export const ACTIONS = {
  LOAD_CORRESPONDENCES: 'LOAD_CORRESPONDENCES',
  UPDATE_RADIO_VALUE: 'UPDATE_RADIO_VALUE',
  SAVE_CHECKBOX_STATE: 'SAVE_CHECKBOX_STATE',
  CLEAR_CHECKBOX_STATE: 'CLEAR_CHECKBOX_STATE'
};
