export const ACTIONS = {
  SET_CORRESPONDENCE: 'SET_CORRESPONDENCE',
  SET_CORRESPONDENCE_DOCUMENTS: 'SET_CORRESPONDENCE_DOCUMENTS',
  SET_PACKAGE_DOCUMENT_TYPE: 'SET_PACKAGE_DOCUMENT_TYPE',
  SET_VETERAN_INFORMATION: 'SET_VETERAN_INFORMATION',
  UPDATE_CMP_INFORMATION: 'UPDATE_CMP_INFORMATION',
  UPDATE_DOCUMENT_TYPE_NAME: 'UPDATE_DOCUMENT_TYPE_NAME',
  REMOVE_PACKAGE_ACTION: 'REMOVE_PACKAGE_ACTION',
  SET_REASON_REMOVE_PACKAGE: 'SET_REASON_REMOVE_PACKAGE',
  SET_AUTO_ASSIGN_BANNER: 'SET_AUTO_ASSIGN_BANNER',
  SET_BATCH_AUTO_ASSIGN_ATTEMPT_ID: 'SET_BATCH_AUTO_ASSIGN_ATTEMPT_ID',
  SET_AUTO_ASSIGN_BUTTON_DISABLED: 'AUTO_ASSIGN_BUTTON_DISABLED'
};
