export const ACTIONS = {
  SET_CORRESPONDENCE: 'SET_CORRESPONDENCE',
  SET_CORRESPONDENCE_DOCUMENTS: 'SET_CORRESPONDENCE_DOCUMENTS',
  SET_PACKAGE_DOCUMENT_TYPE: 'SET_PACKAGE_DOCUMENT_TYPE',
  SET_VETERAN_INFORMATION: 'SET_VETERAN_INFORMATION',
  UPDATE_CMP_INFORMATION: 'UPDATE_CMP_INFORMATION',
  UPDATE_DOCUMENT_TYPE_NAME: 'UPDATE_DOCUMENT_TYPE_NAME',
};
