---
openapi: 3.0.2
info:
  title: API V1
  version: v1
security:
  - bearer-key: []
servers:
- url: /api/v1/
paths:
  "/cmp":
    $ref: "./v1/upload.yml"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TOKEN
  schemas:
    payload:
      $ref: "./v1/payload.yml"
