---
openapi: 3.0.2
info:
  title: API V1
  version: v1
security:
  - bearer-key: []
servers:
- url: http://localhost:3000
  description: Local Development server
- url: https://appeals.cf.uat.ds.va.gov
  description: UAT/Staging server
paths:
  "/api/v1/cmp":
    $ref: "./v1/upload.yml"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TOKEN
  schemas:
    payload:
      $ref: "./v1/payload.yml"
