---
openapi: 3.0.2
info:
  title: API V1
  version: v1
servers:
- url: https://appeals.cf.uat.ds.va.gov
  description: UAT/Staging server
- url: http://localhost:3000
  description: Local Development server
paths:
  "/api/v1/cmp":
    $ref: "./v1/upload.yml"
components:
  schemas:
    payload:
      $ref: "./v1/payload.yml"
