# frozen_string_literal: true

SearchQueryService::Attributes = Struct.new(
  :aod,
  :power_of_attorney,
  :appellant_date_of_birth,
  :appellant_email_address,
  :appellant_first_name,
  :appellant_full_name,
  :appellant_hearing_email_recipient,
  :appellant_is_not_veteran,
  :appellant_last_name,
  :appellant_middle_name,
  :appellant_party_type,
  :appellant_phone_number,
  :appellant_relationship,
  :appellant_substitution,
  :appellant_suffix,
  :appellant_type,
  :appellant_tz,
  :assigned_attorney,
  :assigned_judge,
  :assigned_to_location,
  :caseflow_veteran_id,
  :contested_claim,
  :decision_date,
  :decision_issues,
  :docket_name,
  :docket_number,
  :external_id,
  :hearings,
  :issues,
  :mst,
  :overtime,
  :pact,
  :paper_case,
  :readable_hearing_request_type,
  :readable_original_hearing_request_type,
  :status,
  :type,
  :veteran_appellant_deceased,
  :veteran_file_number,
  :veteran_full_name,
  :unrecognized_appellant_id,
  :withdrawn,
  keyword_init: true
)
