export const CATEGORIES = {
  UPCOMING_HEARINGS_PAGE: 'Upcoming Hearings',
  DAILY_DOCKET_PAGE: 'Daily Docket',
  HEARING_WORKSHEET_PAGE: 'Hearing Worksheet'
};

export const ACTIONS = {
  EDIT_ISSUE: 'EDIT_ISSUE',
  TOGGLE_PRELIMINARY_IMPRESSION: 'TOGGLE_PRELIMINARY_IMPRESSION'
};
