export const DISPOSITION_OPTIONS = ['Granted', 'Denied', 'DTA Error', 'Dismissed', 'Withdrawn'];

export const ACTIONS = {
  TASK_UPDATE_DECISION_ISSUES_START: 'TASK_UPDATE_DECISION_ISSUES_START',
  TASK_UPDATE_DECISION_ISSUES_SUCCEED: 'TASK_UPDATE_DECISION_ISSUES_SUCCEED',
  TASK_UPDATE_DECISION_ISSUES_FAIL: 'TASK_UPDATE_DECISION_ISSUES_FAIL',
  TASK_DEFAULT_PAGE: 'TASK_DEFAULT_PAGE'
};

export const DECISION_ISSUE_UPDATE_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCEED: 'SUCCEED',
  FAIL: 'FAIL'
}
