export const DISPOSITION_OPTIONS = ['Granted', 'Denied', 'DTA Error', 'Dismissed', 'Withdrawn'];

export const ACTIONS = {
  TASK_UPDATE_DECISION_ISSUES_START: 'TASK_UPDATE_DECISION_ISSUES_START',
  TASK_UPDATE_DECISION_ISSUES_SUCCEED: 'TASK_UPDATE_DECISION_ISSUES_SUCCEED',
  TASK_UPDATE_DECISION_ISSUES_FAIL: 'TASK_UPDATE_DECISION_ISSUES_FAIL',
  TASK_DEFAULT_PAGE: 'TASK_DEFAULT_PAGE',
  STARTED_LOADING_POWER_OF_ATTORNEY_VALUE: 'STARTED_LOADING_POWER_OF_ATTORNEY_VALUE',
  RECEIVED_POWER_OF_ATTORNEY: 'RECEIVED_POWER_OF_ATTORNEY',
  ERROR_ON_RECEIVE_POWER_OF_ATTORNEY_VALUE: 'ERROR_ON_RECEIVE_POWER_OF_ATTORNEY_VALUE',
  SET_POA_REFRESH_ALERT: 'SET_POA_REFRESH_ALERT',
  FETCH_TASK_FILTER_DETAILS_START: 'FETCH_TASK_FILTER_DETAILS_START',
  FETCH_TASK_FILTER_DETAILS_SUCCEED: 'FETCH_TASK_FILTER_DETAILS_SUCCEED',
  FETCH_TASK_FILTER_DETAILS_FAIL: 'FETCH_TASK_FILTER_DETAILS_FAIL',
  FETCH_BUSINESSLINE_INFO_START: 'FETCH_BUSINESSLINE_INFO_START',
  FETCH_BUSINESSLINE_INFO_SUCCEED: 'FETCH_BUSINESSLINE_INFO_SUCCEED',
  FETCH_BUSINESSLINE_INFO_FAIL: 'FETCH_BUSINESSLINE_INFO_FAIL'
};

export const DECISION_ISSUE_UPDATE_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCEED: 'SUCCEED',
  FAIL: 'FAIL'
};

export const BOA_ADDRESS = '425 I St NW, Washington DC, 20001';
export const GENERATE_REPORT_ERROR =
  'An error occurred, please try again. If the problem persists, submit a help desk ticket.';
