export const MTV_SUBMIT_ATTY_REVIEW = 'MTV_SUBMIT_ATTY_REVIEW';
export const MTV_SUBMIT_ATTY_REVIEW_SUCCESS = 'MTV_SUBMIT_ATTY_REVIEW_SUCCESS';
export const MTV_SUBMIT_ATTY_REVIEW_ERROR = 'MTV_SUBMIT_ATTY_REVIEW_ERROR';
export const MTV_SUBMIT_JUDGE_DECISION = 'MTV_SUBMIT_JUDGE_DECISION';
export const MTV_SUBMIT_JUDGE_DECISION_SUCCESS = 'MTV_SUBMIT_JUDGE_DECISION_SUCCESS';
export const MTV_SUBMIT_JUDGE_DECISION_ERROR = 'MTV_SUBMIT_JUDGE_DECISION_ERROR';
