version: 3.16.14.8.b{build}

# Operating system (build VM template)
os: Windows Server 2012

clone_depth: 10

environment:
  matrix:
    - ruby_version: "22-x64"
    - ruby_version: "22"
    - ruby_version: "21-x64"
    - ruby_version: "21"
    - ruby_version: "200-x64"
    - ruby_version: "200"
    - ruby_version: "193"

# scripts that run after cloning repository
install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - git submodule update --init
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  - bundle --version
  - bundle install --jobs=1 --retry=3

build_script:
  - bundle exec rake binary

test_script:
  - bundle exec rake spec
  
artifacts:
  - path: pkg\*.gem

