/* eslint-disable */
export const sample1 = {
  currentIssue1: {
    ratingIssueReferenceId: '826209441170',
    ratingIssueProfileDate: '2019-02-22',
    ratingIssueDiagnosticCode: null,
    decisionIssueId: null,
    approxDecisionDate: '2019-02-26',
    description: 'PTSD',
    rampClaimId: null,
    titleOfActiveReview: null,
    sourceReviewType: null,
    timely: true,
    latestIssuesInChain: [{ id: null,
      approxDecisionDate: '2019-02-26' }],
    isRating: true,
    index: '2',
    notes: 'note!',
    correctionType: 'control'
  },
  intakeData: {
    veteran: { name: 'Anne King',
      fileNumber: '872958715',
      formName: 'King, Anne',
      ssn: '208345737' },
    relationships: [
      { value: 'CLAIMANT_WITH_PVA_AS_VSO',
        displayText: 'Bob Vance, Spouse',
        defaultPayeeCode: '10' },
      { value: '1129318238',
        displayText: 'Cathy Smith, Child',
        defaultPayeeCode: '11' }
    ],
    claimant: '826209',
    veteranIsNotClaimant: false,
    receiptDate: '2019/07/18',
    legacyOptInApproved: false,
    legacyAppeals: [
      {
        vacols_id: '2760964',
        date: '2015-01-07T00:00:00.000-05:00',
        eligible_for_soc_opt_in: false,
        issues: [
          {
            vacols_id: '2760964',
            vacols_sequence_id: 1,
            eligible_for_soc_opt_in: true,
            description: 'Service connection, pancreatitis',
            disposition: 'remanded',
            close_date: '2019-04-16T00:00:00.000-04:00',
            note: 'Itaque adipisci aut ullam voluptas recusandae possimus facilis.'
          }
        ]
      },
      {
        vacols_id: 'LEGACYID',
        date: '2018-07-22T00:00:00.000-04:00',
        eligible_for_soc_opt_in: true,
        issues: [
          {
            vacols_id: 'LEGACYID',
            vacols_sequence_id: 3,
            eligible_for_soc_opt_in: true,
            description:
              'New and material evidence to reopen claim for service connection, degenerative arthritis of the spine',
            disposition: null,
            close_date: null,
            note: null
          },
          {
            vacols_id: 'LEGACYID',
            vacols_sequence_id: 4,
            eligible_for_soc_opt_in: true,
            description:
              'New and material evidence to reopen claim for service connection, intervertebral disc syndrome',
            disposition: null,
            close_date: null,
            note: null
          },
          {
            vacols_id: 'LEGACYID',
            vacols_sequence_id: 5,
            eligible_for_soc_opt_in: true,
            description: 'New and material evidence to reopen claim for service connection, ankylosis of hip',
            disposition: null,
            close_date: null,
            note: null
          },
          {
            vacols_id: 'LEGACYID',
            vacols_sequence_id: 1,
            eligible_for_soc_opt_in: true,
            description: 'New and material evidence to reopen claim for service connection, ankylosing spondylitis',
            disposition: null,
            close_date: null,
            note: null
          },
          {
            vacols_id: 'LEGACYID',
            vacols_sequence_id: 2,
            eligible_for_soc_opt_in: true,
            description: 'New and material evidence to reopen claim for service connection, spinal fusion',
            disposition: null,
            close_date: null,
            note: null
          }
        ]
      }
    ],
    ratings: [
      {
        participant_id: '826209',
        profile_date: '2019-07-25T21:28:48.159Z',
        promulgation_date: '2019-06-25',
        issues: [
          {
            participant_id: '826209',
            reference_id: '826209532165',
            decision_text:
              'Service connection for Emphysema is granted with an evaluation of 100 percent effective June 1, 2013.',
            promulgation_date: '2019-06-25',
            profile_date: '2019-07-25T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209346110',
            decision_text:
              "Basic eligibility to Dependents' Educational Assistance is established from October 1, 2017.",
            promulgation_date: '2019-06-25',
            profile_date: '2019-07-25T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2019-07-23T21:28:48.159Z',
        promulgation_date: '2019-03-03',
        issues: [
          {
            participant_id: '826209',
            reference_id: '826209836298',
            decision_text:
              'In mei labore oportere mediocritatem, vel ex dicta quidam corpora, fierent explicari liberavisse ei quo.',
            promulgation_date: '2019-03-03',
            profile_date: '2019-07-23T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209477428',
            decision_text: 'Vel malis impetus ne, vim cibo appareat scripserit ne, qui lucilius consectetuer ex.',
            promulgation_date: '2019-03-03',
            profile_date: '2019-07-23T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209909463',
            decision_text: 'Cu unum partiendo sadipscing has, eius explicari ius no.',
            promulgation_date: '2019-03-03',
            profile_date: '2019-07-23T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209649891',
            decision_text: 'Cu unum partiendo sadipscing has, eius explicari ius no.',
            promulgation_date: '2019-03-03',
            profile_date: '2019-07-23T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209227838',
            decision_text: 'Cibo pertinax hendrerit vis et, legendos euripidis no ius, ad sea unum harum.',
            promulgation_date: '2019-03-03',
            profile_date: '2019-07-23T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2019-07-24T21:28:48.159Z',
        promulgation_date: '2019-03-01',
        issues: [
          {
            participant_id: '826209',
            reference_id: '826209999361',
            decision_text:
              'Lorem ipsum dolor sit amet, paulo scaevola abhorreant mei te, ex est mazim ornatus, at pro causae maiestatis.',
            promulgation_date: '2019-03-01',
            profile_date: '2019-07-24T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209183561',
            decision_text: 'Inani movet maiestatis nec no, verear periculis signiferumque in sit.',
            promulgation_date: '2019-03-01',
            profile_date: '2019-07-24T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '82620984665',
            decision_text: 'Et nibh euismod recusabo duo. Ne zril labitur eum, ei sit augue impedit detraxit.',
            promulgation_date: '2019-03-01',
            profile_date: '2019-07-24T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209381567',
            decision_text: 'Usu et praesent suscipiantur, mea mazim timeam liberavisse et.',
            promulgation_date: '2019-03-01',
            profile_date: '2019-07-24T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209303648',
            decision_text: 'At dicit omnes per, vim tale tota no.',
            promulgation_date: '2019-03-01',
            profile_date: '2019-07-24T21:28:48.159Z',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2019-02-22',
        promulgation_date: '2019-02-26',
        issues: [
          {
            participant_id: '826209',
            reference_id: '826209597423',
            decision_text: 'Left knee',
            promulgation_date: '2019-02-26',
            profile_date: '2019-02-22',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209920000',
            decision_text: 'Right knee',
            promulgation_date: '2019-02-26',
            profile_date: '2019-02-22',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209441170',
            decision_text: 'PTSD',
            promulgation_date: '2019-02-26',
            profile_date: '2019-02-22',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: 'in-active-review-ref-id',
            decision_text: 'This rating is in active review',
            promulgation_date: '2019-02-26',
            profile_date: '2019-02-22',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: '826209942179',
            decision_text: 'I am on a completed Higher Level Review',
            promulgation_date: '2019-02-26',
            profile_date: '2019-02-22',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: '854131' }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2019-02-09',
        promulgation_date: '2019-02-14',
        issues: [
          {
            participant_id: '826209',
            reference_id: 'before_ama_ref_id',
            decision_text: 'Issue before AMA not from a RAMP Review',
            promulgation_date: '2019-02-14',
            profile_date: '2019-02-09',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          },
          {
            participant_id: '826209',
            reference_id: 'ramp_reference_id',
            decision_text: 'Issue before AMA from a RAMP Review',
            promulgation_date: '2019-02-14',
            profile_date: '2019-02-09',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: true
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2018-06-20',
        promulgation_date: '2018-06-25',
        issues: [
          {
            participant_id: '826209',
            reference_id: '826209918301',
            decision_text: 'Old injury',
            promulgation_date: '2018-06-25',
            profile_date: '2018-06-20',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: false
          }
        ]
      },
      {
        participant_id: '826209',
        profile_date: '2017-10-12',
        promulgation_date: '2017-10-17',
        issues: [
          {
            participant_id: '826209',
            reference_id: 'before_test_ama_ref_id',
            decision_text: 'Issue before test AMA not from a RAMP Review',
            promulgation_date: '2017-10-17',
            profile_date: '2017-10-12',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: false
          },
          {
            participant_id: '826209',
            reference_id: 'ramp_reference_id',
            decision_text: 'Issue before test AMA from a RAMP Review',
            promulgation_date: '2017-10-17',
            profile_date: '2017-10-12',
            ramp_claim_id: null,
            rba_contentions_data: [{ prfil_dt: null,
              cntntn_id: null }],
            associated_end_products: [],
            diagnostic_code: null,
            benefit_type: 'compensation',
            timely: false
          }
        ]
      }
    ],
    requestIssues: [
      {
        id: 135,
        rating_issue_reference_id: '826209346110',
        rating_issue_profile_date: '2019-02-22',
        description: 'Left knee',
        contention_text: 'Left knee',
        approx_decision_date: '2019-06-25',
        category: null,
        notes: '',
        is_unidentified: null,
        ramp_claim_id: null,
        vacols_id: null,
        vacols_sequence_id: null,
        vacols_issue: null,
        ineligible_reason: null,
        ineligible_due_to_id: null,
        decision_review_title: 'Higher-Level Review',
        title_of_active_review: null,
        contested_decision_issue_id: null,
        withdrawal_date: '2019-07-18T20:00:00.000-04:00',
        contested_issue_description: 'Left knee',
        end_product_cleared: null,
        end_product_code: '930AMAHRC'
      },
      {
        id: 136,
        rating_issue_reference_id: '826209346110',
        rating_issue_profile_date: '2019-02-22',
        description: 'Left knee',
        contention_text: 'Left knee',
        approx_decision_date: '2019-06-25',
        category: null,
        notes: '',
        is_unidentified: null,
        ramp_claim_id: null,
        vacols_id: null,
        vacols_sequence_id: null,
        vacols_issue: null,
        ineligible_reason: null,
        ineligible_due_to_id: null,
        decision_review_title: 'Higher-Level Review',
        title_of_active_review: null,
        contested_decision_issue_id: null,
        withdrawal_date: '2019-07-18T20:00:00.000-04:00',
        contested_issue_description: 'Left knee',
        end_product_cleared: null,
        end_product_code: '930AMAHRC'
      }
    ],
    decisionIssues: [],
    activeNonratingRequestIssues: [],
    contestableIssuesByDate: [
      {
        ratingIssueReferenceId: '826209597423',
        ratingIssueProfileDate: '2019-02-22',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-26',
        description: 'Left knee',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-26' }],
        isRating: true,
        index: '0'
      },
      {
        ratingIssueReferenceId: '826209920000',
        ratingIssueProfileDate: '2019-02-22',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-26',
        description: 'Right knee',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-26' }],
        isRating: true,
        index: '1'
      },
      {
        ratingIssueReferenceId: '826209441170',
        ratingIssueProfileDate: '2019-02-22',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-26',
        description: 'PTSD',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-26' }],
        isRating: true,
        index: '2'
      },
      {
        ratingIssueReferenceId: 'in-active-review-ref-id',
        ratingIssueProfileDate: '2019-02-22',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-26',
        description: 'This rating is in active review',
        rampClaimId: null,
        titleOfActiveReview: 'Higher-Level Review',
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-26' }],
        isRating: true,
        index: '3'
      },
      {
        ratingIssueReferenceId: '826209942179',
        ratingIssueProfileDate: '2019-02-22',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-26',
        description: 'I am on a completed Higher Level Review',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: 'HigherLevelReview',
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-26' }],
        isRating: true,
        index: '4'
      },
      {
        ratingIssueReferenceId: 'before_ama_ref_id',
        ratingIssueProfileDate: '2019-02-09',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-14',
        description: 'Issue before AMA not from a RAMP Review',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-14' }],
        isRating: true,
        index: '5'
      },
      {
        ratingIssueReferenceId: 'ramp_reference_id',
        ratingIssueProfileDate: '2019-02-09',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2019-02-14',
        description: 'Issue before AMA from a RAMP Review',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: true,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2019-02-14' }],
        isRating: true,
        index: '6'
      },
      {
        ratingIssueReferenceId: '826209918301',
        ratingIssueProfileDate: '2018-06-20',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2018-06-25',
        description: 'Old injury',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: false,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2018-06-25' }],
        isRating: true,
        index: '7'
      },
      {
        ratingIssueReferenceId: 'before_test_ama_ref_id',
        ratingIssueProfileDate: '2017-10-12',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2017-10-17',
        description: 'Issue before test AMA not from a RAMP Review',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: false,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2017-10-17' }],
        isRating: true,
        index: '8'
      },
      {
        ratingIssueReferenceId: 'ramp_reference_id',
        ratingIssueProfileDate: '2017-10-12',
        ratingIssueDiagnosticCode: null,
        decisionIssueId: null,
        approxDecisionDate: '2017-10-17',
        description: 'Issue before test AMA from a RAMP Review',
        rampClaimId: null,
        titleOfActiveReview: null,
        sourceReviewType: null,
        timely: false,
        latestIssuesInChain: [{ id: null,
          approxDecisionDate: '2017-10-17' }],
        isRating: true,
        index: '9'
      }
    ],
    editIssuesUrl: '/higher_level_reviews/7dccd357-009c-4744-b986-4c46ad7c029e/edit',
    veteranValid: true,
    veteranInvalidFields: { veteranMissingFields: '',
      veteranAddressTooLong: false,
      veteranAddressInvalidFields: false,
      veteranCityInvalidFields: false,
      veteranDateOfBirthInvalid: false
    },
    processedInCaseflow: false,
    benefitType: 'compensation',
    payeeCode: null,
    hasClearedRatingEp: true,
    hasClearedNonratingEp: false,
    formType: 'higher_level_review',
    sameOffice: false,
    informalConference: false,
    contestableIssues: {
      '2019-02-26': {
        0: {
          ratingIssueReferenceId: '826209597423',
          ratingIssueProfileDate: '2019-02-22',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-26',
          description: 'Left knee',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-26' }],
          isRating: true,
          index: '0'
        },
        1: {
          ratingIssueReferenceId: '826209920000',
          ratingIssueProfileDate: '2019-02-22',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-26',
          description: 'Right knee',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-26' }],
          isRating: true,
          index: '1'
        },
        2: {
          ratingIssueReferenceId: '826209441170',
          ratingIssueProfileDate: '2019-02-22',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-26',
          description: 'PTSD',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-26' }],
          isRating: true,
          index: '2'
        },
        3: {
          ratingIssueReferenceId: 'in-active-review-ref-id',
          ratingIssueProfileDate: '2019-02-22',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-26',
          description: 'This rating is in active review',
          rampClaimId: null,
          titleOfActiveReview: 'Higher-Level Review',
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-26' }],
          isRating: true,
          index: '3'
        },
        4: {
          ratingIssueReferenceId: '826209942179',
          ratingIssueProfileDate: '2019-02-22',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-26',
          description: 'I am on a completed Higher Level Review',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: 'HigherLevelReview',
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-26' }],
          isRating: true,
          index: '4'
        }
      },
      '2019-02-14': {
        5: {
          ratingIssueReferenceId: 'before_ama_ref_id',
          ratingIssueProfileDate: '2019-02-09',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-14',
          description: 'Issue before AMA not from a RAMP Review',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-14' }],
          isRating: true,
          index: '5'
        },
        6: {
          ratingIssueReferenceId: 'ramp_reference_id',
          ratingIssueProfileDate: '2019-02-09',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2019-02-14',
          description: 'Issue before AMA from a RAMP Review',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: true,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2019-02-14' }],
          isRating: true,
          index: '6'
        }
      },
      '2018-06-25': {
        7: {
          ratingIssueReferenceId: '826209918301',
          ratingIssueProfileDate: '2018-06-20',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2018-06-25',
          description: 'Old injury',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: false,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2018-06-25' }],
          isRating: true,
          index: '7'
        }
      },
      '2017-10-17': {
        8: {
          ratingIssueReferenceId: 'before_test_ama_ref_id',
          ratingIssueProfileDate: '2017-10-12',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2017-10-17',
          description: 'Issue before test AMA not from a RAMP Review',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: false,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2017-10-17' }],
          isRating: true,
          index: '8'
        },
        9: {
          ratingIssueReferenceId: 'ramp_reference_id',
          ratingIssueProfileDate: '2017-10-12',
          ratingIssueDiagnosticCode: null,
          decisionIssueId: null,
          approxDecisionDate: '2017-10-17',
          description: 'Issue before test AMA from a RAMP Review',
          rampClaimId: null,
          titleOfActiveReview: null,
          sourceReviewType: null,
          timely: false,
          latestIssuesInChain: [{ id: null,
            approxDecisionDate: '2017-10-17' }],
          isRating: true,
          index: '9'
        }
      }
    },
    claimId: '7dccd357-009c-4744-b986-4c46ad7c029e',
    featureToggles: {
      useAmaActivationDate: true,
      correctClaimReviews: true,
      unidentifiedIssueDecisionDate: true,
      attorneyFees: true
    },
    addIssuesModalVisible: false,
    nonRatingRequestIssueModalVisible: false,
    unidentifiedIssuesModalVisible: false,
    addedIssues: [
      {
        id: '135',
        isRating: true,
        ratingIssueReferenceId: '826209346110',
        ratingIssueProfileDate: '2019-02-22T00:00:00.000Z',
        approxDecisionDate: '2019-06-25',
        decisionIssueId: null,
        notes: '',
        description: 'Left knee',
        ineligibleReason: null,
        ineligibleDueToId: null,
        titleOfActiveReview: null,
        contentionText: 'Left knee',
        rampClaimId: null,
        vacolsId: null,
        vacolsSequenceId: null,
        vacolsIssue: null,
        endProductCleared: null,
        endProductCode: '930AMAHRC',
        withdrawalDate: '07/19/2019'
      },
      {
        id: '136',
        isRating: true,
        ratingIssueReferenceId: '826209346110',
        ratingIssueProfileDate: '2019-02-22T00:00:00.000Z',
        approxDecisionDate: '2019-06-25',
        decisionIssueId: null,
        notes: '',
        description: 'Left knee',
        ineligibleReason: null,
        ineligibleDueToId: null,
        titleOfActiveReview: null,
        contentionText: 'Left knee',
        rampClaimId: null,
        vacolsId: null,
        vacolsSequenceId: null,
        vacolsIssue: null,
        endProductCleared: null,
        endProductCode: '930AMAHRC',
        withdrawalDate: '07/19/2019'
      }
    ],
    originalIssues: [
      {
        id: '135',
        isRating: true,
        ratingIssueReferenceId: '826209346110',
        ratingIssueProfileDate: '2019-02-22T00:00:00.000Z',
        approxDecisionDate: '2019-06-25',
        decisionIssueId: null,
        notes: '',
        description: 'Left knee',
        ineligibleReason: null,
        ineligibleDueToId: null,
        titleOfActiveReview: null,
        contentionText: 'Left knee',
        rampClaimId: null,
        vacolsId: null,
        vacolsSequenceId: null,
        vacolsIssue: null,
        endProductCleared: null,
        endProductCode: '930AMAHRC',
        withdrawalDate: '07/19/2019'
      },
      {
        id: '136',
        isRating: true,
        ratingIssueReferenceId: '826209346110',
        ratingIssueProfileDate: '2019-02-22T00:00:00.000Z',
        approxDecisionDate: '2019-06-25',
        decisionIssueId: null,
        notes: '',
        description: 'Left knee',
        ineligibleReason: null,
        ineligibleDueToId: null,
        titleOfActiveReview: null,
        contentionText: 'Left knee',
        rampClaimId: null,
        vacolsId: null,
        vacolsSequenceId: null,
        vacolsIssue: null,
        endProductCleared: null,
        endProductCode: '930AMAHRC',
        withdrawalDate: '07/19/2019'
      }
    ],
    requestStatus: { requestIssuesUpdate: 'NOT_STARTED' },
    requestIssuesUpdateErrorCode: null,
    afterIssues: null,
    beforeIssues: null,
    updatedIssues: null
  }
};
