// actions
export const CHANGE_EMPLOYEE_COUNT = 'CHANGE_EMPLOYEE_COUNT';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SET_USER_QUOTAS_FROM_API = 'SET_USER_QUOTAS_FROM_API';
