// actions
export const CHANGE_EMPLOYEE_COUNT = 'CHANGE_EMPLOYEE_COUNT';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REQUEST_USER_QUOTAS_SUCCESS = 'REQUEST_USER_QUOTAS_SUCCESS';
export const BEGIN_EDIT_TASK_COUNT = 'BEGIN_EDIT_TASK_COUNT';
export const CHANGE_NEW_TASK_COUNT = 'CHANGE_NEW_TASK_COUNT';
export const SAVE_TASK_COUNT = 'SAVE_TASK_COUNT';
