// actions
export const CHANGE_EMPLOYEE_COUNT = 'CHANGE_EMPLOYEE_COUNT';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REQUEST_USER_QUOTAS_SUCCESS = 'REQUEST_USER_QUOTAS_SUCCESS';
