export const ACTIONS = {
  RECEIVE_REGIONAL_OFFICES: 'RECEIVE_REGIONAL_OFFICES',
  REGIONAL_OFFICE_CHANGE: 'REGIONAL_OFFICE_CHANGE',
  RECEIVE_HEARING_DAYS: 'RECEIVE_HEARING_DAYS',
  RECEIVE_DROPDOWN_DATA: 'RECEIVE_DROPDOWN_DATA',
  FETCH_DROPDOWN_DATA: 'FETCH_DROPDOWN_DATA',
  CHANGE_FORM_DATA: 'CHANGE_FORM_DATA',
  DROPDOWN_ERROR: 'DROPDOWN_ERROR',
  REMOVE_ALERTS_WITH_EXPIRATION: 'REMOVE_ALERTS_WITH_EXPIRATION',
  REMOVE_ALERTS_WITHOUT_EXPIRATION: 'REMOVE_ALERTS_WITHOUT_EXPIRATION',
  RECEIVE_ALERTS: 'RECEIVE_ALERTS'
};
