export const ACTIONS = {
  RECEIVE_REGIONAL_OFFICES: 'RECEIVE_REGIONAL_OFFICES',
  REGIONAL_OFFICE_CHANGE: 'REGIONAL_OFFICE_CHANGE',
  RECEIVE_HEARING_DAYS: 'RECEIVE_HEARING_DAYS',
  HEARING_DAY_CHANGE: 'HEARING_DAY_CHANGE',
  HEARING_TIME_CHANGE: 'HEARING_TIME_CHANGE',
  RECEIVE_DROPDOWN_DATA: 'RECEIVE_DROPDOWN_DATA',
  FETCH_DROPDOWN_DATA: 'FETCH_DROPDOWN_DATA'
};
