#!/bin/bash
# git command to run codeclimate on in-flight code changes
# accepts a file path or will run codeclimate on the entire project
file=$1

docker pull codeclimate/codeclimate

docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate help

# install engines in .codeclimate.yml
codeclimate engines:install

# run tests for single file or entire project
if [ ! -z "$1" ]; then
# analyze changes on file
  echo "running codeClimate CLI for $file"
  codeclimate analyze $file
else
  echo "running CodeClimate CLI for entire project"
  codeclimate analyze
fi
