openapi: 3.0.0
info:
  title: Decision Reviews
  description: API version 0 for Decision Reviews provided by the Lighthouse Project
  version: 3.0.0
servers:
  - url: /api/{version}
paths:
  /higher_level_reviews:
    post:
      summary: Creates a Higher-Level Review.
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              required:
                - data
                # included (NOT required)
              properties:
                data:
                  type: object
                  required:
                    - type
                    - attributes
                    - relationships
                  properties:
                    type:
                      type: string
                      enum: [higher_level_review]
                    attributes:
                      type: object
                      required:
                        - receipt_date
                        - informal_conference
                        - same_office
                        - legacy_opt_in_approved
                        - benefit_type
                      properties:
                        receipt_date:
                          type: string
                          format: date
                        informal_conference:
                          type: boolean
                        same_office:
                          type: boolean
                        legacy_opt_in_approved:
                          type: boolean
                        benefit_type:
                          type: string
                          enum:
                            - compensation
                            - pension
                            - fiduciary
                            - insurance
                            - education
                            - voc_rehab
                            - loan_guaranty
                            - vha
                            - nca
                    relationships:
                      type: object
                      required:
                        - veteran
                        # claimant (NOT required)
                      properties:
                        veteran:
                          type: object
                          required:
                            - data
                          properties:
                            data:
                              type: object
                              required:
                                - type
                                - id
                              properties:
                                type:
                                  type: string
                                  enum: [veteran]
                                id: # veteran_file_number
                                  type: string
                        claimant: # if claimant is not included, the veteran is the claimant (and their participantID is looked up)
                          type: object
                          required:
                            - data
                          properties:
                            data:
                              type: object
                              required:
                                - type
                                - id
                                - meta
                              properties:
                                type:
                                  type: string
                                  enum: [claimant]
                                id: # participantID
                                  type: string
                                meta:
                                  type: object
                                  required:
                                    - payee_code
                                  properties:
                                    payee_code:
                                      $ref: "#/components/schemas/payee_code"
                included:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - attributes
                    properties:
                      type:
                        type: string
                        enum: [request_issue]
                      attributes:
                        type: object
                        required:
                          - decision_text
                          - decision_date
                          # withdrawal_date (NOT required)
                          # nonrating_issue_category (NOT required)
                        properties:
                          decision_text:
                            type: string
                          decision_date:
                            type: string
                            format: date
                          withdrawal_date:
                            type: string
                            format: date
                          nonrating_issue_category:
                            $ref: "#/components/schemas/nonrating_issue_category"
      responses:
        '202':
          description: Created
        '400':
          description: Invalid Request
        '500':
          description: Failed
  /higher_level_reviews/status/{id}:
    get:
      summary:
        responses:
          '200':
            description: Status found
            content:
              application/vnd.api+json:
                schema:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                          description: Will be "higherLevelReview"
                        attributes:
                          type: object
                          properties:
                            appealIds:
                              type: array
                              items:
                                type: string
                            updated:
                              type: string
                              format: date-time
                            incompleteHistory:
                              type: boolean
                            active:
                              type: boolean
                            description:
                              type: string
                            location:
                              type: string
                            aoj:
                              type: string
                            programArea:
                              type: string
                            status:
                              type: object
                              properties:
                                type:
                                  type: string
                                details:
                                  type: object
                                  properties:
                                    description:
                                      type: string
                                    disposition:
                                      type: string
                            alerts:
                              type: array
                              items:
                                type: object
                            issues:
                              type: array
                              items:
                                type: object
                                properties:
                                  active:
                                    type: boolean
                                  lastAction:
                                    type: string
                                    format: date-time
                                  date:
                                    type: string
                                    format: date-time
                                  description:
                                    type: string
                                  diagnosticCode:
                                    type: string
                            events:
                              type: array
                              items:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  date:
                                    type: string
                                    format: date-time
                            evidence:
                              type: array
                              description: Will be empty https://github.com/department-of-veterans-affairs/caseflow/blob/c57d95f6ea11985b7658782cc82005107e9c3156/app/models/serializers/v2/appeal_status_serializer.rb#L37
          '400':
            description: Invalid Request
          '500':
            description: Failed
components:
  schemas:
    nonrating_issue_category:
      type: string
      enum:
        # for benefit type:  compensation
        - Unknown issue category
        - Apportionment
        - Incarceration Adjustments
        - Audit Error Worksheet (DFAS)
        - Active Duty Adjustments
        - Drill Pay Adjustments
        - Character of discharge determinations
        - Income/net worth (pension)
        - Dependent child - Adopted
        - Dependent child - Stepchild
        - Dependent child - Biological
        - Dependency Spouse - Common law marriage
        - Dependency Spouse - Inference of marriage
        - Dependency Spouse - Deemed valid marriage
        - Military Retired Pay
        - Contested Claims (other than apportionment)
        - Lack of Qualifying Service
        - Other non-rated
        # for benefit type:  pension
        - Eligibility | Wartime service
        - Eligibility | Veteran Status
        - Income/Net Worth | Countable Income
        - Income/Net Worth | Residential Lot Size
        - Income/Net Worth | Medical Expense Deductions
        - Effective date | Liberalizing Legislation
        - Effective date | 3.400(b)(ii)(B)
        - Dependent Eligibility | Adoption
        - Dependent Eligibility | Stepchild
        - Dependent Eligibility | School child
        - Dependent Eligibility | Validity of marriage
        - Dependent Eligibility | Parent(s)
        - Dependent Eligibility | Other
        - Penalty Period
        - Post Award Audit
        - Overpayment | Validity of debt
        - Overpayment | Waiver
        - Apportionment
        - Survivors pension eligibility
        - Burial Benefits - NSC Burial
        - Burial Benefits - Plot or Interment Allowance
        - Burial Benefits - Transportation Allowance
        - Burial Benefits - VA Hospitalization Death
        # for benefit type:  fiduciary
        - Appointment of a Fiduciary (38 CFR 13.100)
        - Removal of a Fiduciary (38 CFR 13.500)
        - Misuse Determination (38 CFR 13.400)
        - RO Director Reconsideration of Misuse Determination (13.400(d))
        - P&F Director's Negligence Determination for Benefits Reissuance (13.410)
        # for benefit type:  voc_rehab
        - Basic Eligibility
        - Entitlement to Services
        - Plan/Goal Selection
        - Equipment/Supply Purchases
        - Additional Training
        - Change of Program
        - Feasibility to Pursue a Vocational Goal
        - Training Facility Selection
        - Subsistence Allowance
        - Employment Adjustment Allowance
        - Entitlement Extension
        - Advance from the Revolving Fund Loan
        - Retroactive Induction
        - Retroactive Reimbursement
        - Successful Closure of Case
        - Discontinue Services
        - Interruption of Services
        # for benefit type:  education
        - Accrued
        - Eligibility | 38 U.S.C. ch. 30
        - Eligibility | 38 U.S.C. ch. 35
        - Eligibility | 38 U.S.C. ch. 32
        - Eligibility | 38 U.S.C. ch. 33
        - Eligibility | 38 U.S.C. ch. 1606
        - Entitlement | 38 U.S.C. ch. 30
        - Entitlement | 38 U.S.C. ch. 35
        - Entitlement | 38 U.S.C. ch. 32
        - Entitlement | 38 U.S.C. ch. 33
        - Entitlement | 38 U.S.C. ch. 1606
        - Effective Date of Award | 38 U.S.C. ch. 35
        - Payment | 38 U.S.C. ch. 30
        - Payment | 38 U.S.C. ch. 35
        - Payment | 38 U.S.C. ch. 32
        - Payment | 38 U.S.C. ch. 33
        - Payment | 38 U.S.C. ch. 1606
        - Overpayment | Validity of debt
        - Vet Tec
        - Delimiting Date Issues | 38 U.S.C. ch. 30
        - Delimiting Date Issues | 38 U.S.C. ch. 35
        - Delimiting Date Issues | 38 U.S.C. ch. 32
        - Delimiting Date Issues | 38 U.S.C. ch. 33
        - Delimiting Date Issues | 38 U.S.C. ch. 1606
        - Other
        # for benefit type:  insurance
        - Waiver of premiums (1912-1914) | Date of total disability
        - Waiver of premiums (1912-1914) | Effective date
        - Waiver of premiums (1912-1914) | TDIP (1915)
        - Waiver of premiums (1912-1914) | Other
        - Reinstatement | Medically Qualified
        - Reinstatement | Other
        - RH (1922(a) S-DVI) | Timely application
        - RH (1922(a) S-DVI) | Medically qualified
        - RH (1922(a) S-DVI) | Discharged before 4/25/51
        - RH (1922(a) S-DVI) | Other
        - SRH (1922(b) S-DVI) | Timely application
        - SRH (1922(b) S-DVI) | Over age 65
        - SRH (1922(b) S-DVI) | Other
        - VMLI (2106) | LOC/Reverse Mortgage
        - VMLI (2106) | Over age 70
        - VMLI (2106) | Death Award
        - VMLI (2106) | Other
        - Contested death claim | Relationships
        - Contested death claim | Testamentary capacity
        - Contested death claim | Undue influence
        - Contested death claim | Intent of insured
        - Contested death claim | Other
        - Other
        # for benefit type:  loan_guaranty
        - Basic eligibility - Certificate of Eligibility (COE) was denied for use of benefit
        - Validity of debt - Existing debt indicated from loan termination is incorrect as stated
        - Waiver of indebtedness - Existing debt should be waived to allow issuance of COE
        - Restoration of entitlement - Remove a previous loan that was paid-in-full to allow all available entitlement on the COE
        - Other
        # for benefit type:  nca
        - Entitlement | Reserves/National Guard
        - Entitlement | Less than 24 months
        - Entitlement | Character of service
        - Entitlement | Merchant Marine
        - Entitlement | No military information
        - Entitlement | Cadet (service academies)
        - Entitlement | Unmarried Adult Child
        - Entitlement | Allied forces and non-citizens
        - Entitlement | Pre-need
        - Entitlement | Spouse/Surving Spouse
        - Entitlement | Non-qualifying service
        - Entitlement | ABMC/overseas burial
        - Entitlement | Pre-WWI/burial site unknown
        - Entitlement | Marked grave (death prior to 10-18-78)
        - Entitlement | Marked grave (death on/after 10-18-78 to 10-31-90)
        - Entitlement | Other
        - Entitlement | Voided Enlistment
        - Entitlement | Benefit Already Provided
        - Entitlement | Confederate IMO
        - Entitlement | Cremains not interred
        - Entitlement | Historic marker deemed serviceable
        - Entitlement | Medallion (no grave)
        - Entitlement | Medallion (unmarked grave)
        - Entitlement | Parent
        - Entitlement | Replacement
        - Entitlement | Unauthorized applicant
        - Entitlement | Hmong
        - Entitlement | Medallion (monetary allowance)
        - Entitlement | IMO in NC
        # for benefit type:  vha
        - Eligibility for Treatment | Dental
        - Eligibility for Treatment | Other
        - Beneficiary Travel | Mileage
        - Beneficiary Travel | Common Carrier
        - Beneficiary Travel | Special Mode
        - Eligibility for Fee Basis Care
        - Indebtedness | Validity of Debt
        - Indebtedness | Waiver
        - Level of Priority for Treatment
        - Clothing Allowance ยง 3.810(b) Certification
        - Prosthetics Services
        - Family Member Services | CHAMPVA Eligibility
        - Family Member Services | CHAMPVA Medical Charges
        - Family Member Services | Foreign Medical Program Medical Charges
        - Family Member Services | Spina Bifida Medical Charges
        - Family Member Services | Camp Lejeune Family Member Eligibility
        - Other
    payee_code:
      type: string
      enum:
        - "00"
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
        - "32"
        - "33"
        - "34"
        - "35"
        - "36"
        - "37"
        - "38"
        - "39"
        - "41"
        - "42"
        - "43"
        - "44"
        - "45"
        - "46"
        - "47"
        - "48"
        - "49"
        - "50"
        - "60"
        - "70"
        - "71"
        - "72"
        - "73"
        - "74"
        - "75"
        - "76"
        - "77"
        - "78"
        - "80"
        - "81"
        - "82"
        - "83"
        - "84"
        - "85"
        - "86"
        - "87"
        - "88"
        - "89"
        - "99"
