export const CLEAR_CASE_LIST_SEARCH = 'CLEAR_CASE_LIST_SEARCH';
export const CLEAR_CASE_LIST_SEARCH_RESULTS = 'CLEAR_CASE_LIST_SEARCH_RESULTS';
export const RECEIVED_APPEALS_USING_VETERAN_ID_SUCCESS = 'RECEIVED_APPEALS_USING_VETERAN_ID_SUCCESS';
export const REQUEST_APPEAL_USING_VETERAN_ID = 'REQUEST_APPEAL_USING_VETERAN_ID';
export const SEARCH_RESULTED_IN_ERROR = 'SEARCH_RESULTED_IN_ERROR';
export const SET_CASE_LIST_SEARCH = 'SET_CASE_LIST_SEARCH';
