export const APPEALS_FETCH_FAILED_INVALID_VETERAN_ID = 'APPEALS_FETCH_FAILED_INVALID_VETERAN_ID';
export const CLEAR_CASE_LIST_SEARCH = 'CLEAR_CASE_LIST_SEARCH';
export const CLEAR_CASE_LIST_SEARCH_RESULTS = 'CLEAR_CASE_LIST_SEARCH_RESULTS';
export const RECEIVED_APPEALS_USING_VETERAN_ID_FAILURE = 'RECEIVED_APPEALS_USING_VETERAN_ID_FAILURE';
export const RECEIVED_APPEALS_USING_VETERAN_ID_SUCCESS = 'RECEIVED_APPEALS_USING_VETERAN_ID_SUCCESS';
export const RECEIVED_NO_APPEALS_USING_VETERAN_ID = 'RECEIVED_NO_APPEALS_USING_VETERAN_ID';
export const REQUEST_APPEAL_USING_VETERAN_ID = 'REQUEST_APPEAL_USING_VETERAN_ID';
export const SET_CASE_LIST_SEARCH = 'SET_CASE_LIST_SEARCH';
