export const ENDPOINT_NAMES = {
  REQUEST_ISSUES_UPDATE: 'request-issues-update',
  EDIT_EP_CLAIM_LABEL: 'edit-ep-claim-label',
};

export const ACTIONS = {
  REQUEST_ISSUES_UPDATE_START: 'REQUEST_ISSUES_UPDATE_START',
  REQUEST_ISSUES_UPDATE_SUCCEED: 'REQUEST_ISSUES_UPDATE_SUCCEED',
  REQUEST_ISSUES_UPDATE_FAIL: 'REQUEST_ISSUES_UPDATE_FAIL',
  EDIT_EP_CLAIM_LABEL: 'EDIT_EP_CLAIM_LABEL',
  EDIT_EP_CLAIM_LABEL_FAILED: 'EDIT_EP_CLAIM_LABEL_FAILED',
};
