export const PAGE_PATHS = {
  BEGIN: '/',
  CANCEL_ISSUES: '/cancel'
};

export const ENDPOINT_NAMES = {
  REQUEST_ISSUES_UPDATE: 'request-issues-update'
};

export const ACTIONS = {
  NO_ISSUES_SELECTED_ERROR: 'NO_ISSUES_SELECTED_ERROR',
  REQUEST_ISSUES_UPDATE_START: 'REQUEST_ISSUES_UPDATE_START',
  REQUEST_ISSUES_UPDATE_SUCCEED: 'REQUEST_ISSUES_UPDATE_SUCCEED',
  REQUEST_ISSUES_UPDATE_FAIL: 'REQUEST_ISSUES_UPDATE_FAIL'
};
