export const PAGE_PATHS = {
  BEGIN: '/',
  SELECT_ISSUES: '/select_issues',
  CANCEL_ISSUES: '/cancel'
};

export const ENDPOINT_NAMES = {
  REQUEST_ISSUES_UPDATE: 'request-issues-update'
};

export const ACTIONS = {
  SET_ISSUE_SELECTED: 'SET_ISSUE_SELECTED',
  REQUEST_ISSUES_UPDATE_START: 'REQUEST_ISSUES_UPDATE_START',
  REQUEST_ISSUES_UPDATE_SUCCEED: 'REQUEST_ISSUES_UPDATE_SUCCEED',
  REQUEST_ISSUES_UPDATE_FAIL: 'REQUEST_ISSUES_UPDATE_FAIL'
};

export const REQUEST_STATE = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED'
};
