class AddUpdatedAtIndices < ActiveRecord::Migration[5.1]
  disable_ddl_transaction!

  def change
    add_index :advance_on_docket_motions, :updated_at, algorithm: :concurrently
    add_index :allocations, :updated_at, algorithm: :concurrently
    add_index :api_keys, :updated_at, algorithm: :concurrently
    add_index :appeal_series, :updated_at, algorithm: :concurrently
    add_index :appeals, :updated_at, algorithm: :concurrently
    add_index :attorney_case_reviews, :updated_at, algorithm: :concurrently
    add_index :available_hearing_locations, :updated_at, algorithm: :concurrently
    add_index :board_grant_effectuations, :updated_at, algorithm: :concurrently
    add_index :cached_appeal_attributes, :updated_at, algorithm: :concurrently
    add_index :cached_user_attributes, :updated_at, algorithm: :concurrently
    add_index :certification_cancellations, :updated_at, algorithm: :concurrently
    add_index :certifications, :updated_at, algorithm: :concurrently
    add_index :claim_establishments, :updated_at, algorithm: :concurrently
    add_index :claimants, :updated_at, algorithm: :concurrently
    add_index :claims_folder_searches, :updated_at, algorithm: :concurrently
    add_index :decision_documents, :updated_at, algorithm: :concurrently
    add_index :decision_issues, :updated_at, algorithm: :concurrently
    add_index :dispatch_tasks, :updated_at, algorithm: :concurrently
    add_index :distributed_cases, :updated_at, algorithm: :concurrently
    add_index :distributions, :updated_at, algorithm: :concurrently
    add_index :docket_snapshots, :updated_at, algorithm: :concurrently
    add_index :docket_tracers, :updated_at, algorithm: :concurrently
    add_index :end_product_code_updates, :updated_at, algorithm: :concurrently
    add_index :end_product_establishments, :updated_at, algorithm: :concurrently
    add_index :global_admin_logins, :updated_at, algorithm: :concurrently
    add_index :hearing_appeal_stream_snapshots, :updated_at, algorithm: :concurrently
    add_index :hearing_days, :updated_at, algorithm: :concurrently
    add_index :hearing_issue_notes, :updated_at, algorithm: :concurrently
    add_index :hearing_locations, :updated_at, algorithm: :concurrently
    add_index :hearing_task_associations, :updated_at, algorithm: :concurrently
    add_index :hearings, :updated_at, algorithm: :concurrently
    add_index :higher_level_reviews, :updated_at, algorithm: :concurrently
    add_index :intakes, :updated_at, algorithm: :concurrently
    add_index :job_notes, :updated_at, algorithm: :concurrently
    add_index :judge_case_reviews, :updated_at, algorithm: :concurrently
    add_index :judge_team_roles, :updated_at, algorithm: :concurrently
    add_index :legacy_appeals, :updated_at, algorithm: :concurrently
    add_index :legacy_hearings, :updated_at, algorithm: :concurrently
    add_index :legacy_issue_optins, :updated_at, algorithm: :concurrently
    add_index :messages, :updated_at, algorithm: :concurrently
    add_index :non_availabilities, :updated_at, algorithm: :concurrently
    add_index :organizations, :updated_at, algorithm: :concurrently
    add_index :organizations_users, :updated_at, algorithm: :concurrently
    add_index :people, :updated_at, algorithm: :concurrently
    add_index :post_decision_motions, :updated_at, algorithm: :concurrently
    add_index :ramp_closed_appeals, :updated_at, algorithm: :concurrently
    add_index :ramp_election_rollbacks, :updated_at, algorithm: :concurrently
    add_index :ramp_elections, :updated_at, algorithm: :concurrently
    add_index :ramp_issues, :updated_at, algorithm: :concurrently
    add_index :ramp_refilings, :updated_at, algorithm: :concurrently
    add_index :record_synced_by_jobs, :updated_at, algorithm: :concurrently
    add_index :remand_reasons, :updated_at, algorithm: :concurrently
    add_index :request_decision_issues, :updated_at, algorithm: :concurrently
    add_index :request_issues, :updated_at, algorithm: :concurrently
    add_index :request_issues_updates, :updated_at, algorithm: :concurrently
    add_index :schedule_periods, :updated_at, algorithm: :concurrently
    add_index :special_issue_lists, :updated_at, algorithm: :concurrently
    add_index :supplemental_claims, :updated_at, algorithm: :concurrently
    add_index :tags, :updated_at, algorithm: :concurrently
    add_index :task_timers, :updated_at, algorithm: :concurrently
    add_index :tasks, :updated_at, algorithm: :concurrently
    add_index :team_quotas, :updated_at, algorithm: :concurrently
    add_index :transcriptions, :updated_at, algorithm: :concurrently
    add_index :user_quotas, :updated_at, algorithm: :concurrently
    add_index :users, :updated_at, algorithm: :concurrently
    add_index :vbms_uploaded_documents, :updated_at, algorithm: :concurrently
    add_index :veterans, :updated_at, algorithm: :concurrently
    add_index :virtual_hearings, :updated_at, algorithm: :concurrently
    add_index :vso_configs, :updated_at, algorithm: :concurrently
    add_index :worksheet_issues, :updated_at, algorithm: :concurrently
  end
end
