class AddForeignKeys < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key "advance_on_docket_motions", "people", name: "advance_on_docket_motions_person_id_fk"
    add_foreign_key "allocations", "schedule_periods", name: "allocations_schedule_period_id_fk"
    add_foreign_key "annotations", "documents", name: "annotations_document_id_fk"
    add_foreign_key "attorney_case_reviews", "users", column: "attorney_id", name: "attorney_case_reviews_attorney_id_fk"
    add_foreign_key "attorney_case_reviews", "users", column: "reviewing_judge_id", name: "attorney_case_reviews_reviewing_judge_id_fk"
    add_foreign_key "attorney_case_reviews", "tasks", name: "attorney_case_reviews_task_id_fk"
    add_foreign_key "available_hearing_locations", "veterans", column: "veteran_file_number", primary_key: "file_number", name: "available_hearing_locations_veteran_file_number_fk"
    add_foreign_key "board_grant_effectuations", "appeals", name: "board_grant_effectuations_appeal_id_fk"
    add_foreign_key "board_grant_effectuations", "decision_documents", name: "board_grant_effectuations_decision_document_id_fk"
    add_foreign_key "board_grant_effectuations", "end_product_establishments", name: "board_grant_effectuations_end_product_establishment_id_fk"
    add_foreign_key "board_grant_effectuations", "decision_issues", column: "granted_decision_issue_id", name: "board_grant_effectuations_granted_decision_issue_id_fk"
    add_foreign_key "cached_appeal_attributes", "tasks", column: "appeal_id", name: "cached_appeal_attributes_appeal_id_fk"
    add_foreign_key "cached_appeal_attributes", "legacy_appeals", column: "vacols_id", primary_key: "vacols_id", name: "cached_appeal_attributes_vacols_id_fk"
    add_foreign_key "cavc_remands", "users", column: "created_by_id", name: "cavc_remands_created_by_id_fk"
    add_foreign_key "cavc_remands", "appeals", column: "remand_appeal_id", name: "cavc_remands_remand_appeal_id_fk"
    add_foreign_key "cavc_remands", "appeals", column: "source_appeal_id", name: "cavc_remands_source_appeal_id_fk"
    add_foreign_key "cavc_remands", "users", column: "updated_by_id", name: "cavc_remands_updated_by_id_fk"
    add_foreign_key "certification_cancellations", "certifications", name: "certification_cancellations_certification_id_fk"
    add_foreign_key "claim_establishments", "dispatch_tasks", column: "task_id", name: "claim_establishments_task_id_fk"
    add_foreign_key "dispatch_tasks", "legacy_appeals", column: "appeal_id", name: "dispatch_tasks_appeal_id_fk"
    add_foreign_key "distributed_cases", "distributions", name: "distributed_cases_distribution_id_fk"
    add_foreign_key "distributed_cases", "tasks", name: "distributed_cases_task_id_fk"
    add_foreign_key "distributions", "users", column: "judge_id", name: "distributions_judge_id_fk"
    add_foreign_key "docket_tracers", "docket_snapshots", name: "docket_tracers_docket_snapshot_id_fk"
    add_foreign_key "document_views", "documents", name: "document_views_document_id_fk"
    add_foreign_key "documents_tags", "documents", name: "documents_tags_document_id_fk"
    add_foreign_key "documents_tags", "tags", name: "documents_tags_tag_id_fk"
    add_foreign_key "end_product_code_updates", "end_product_establishments", name: "end_product_code_updates_end_product_establishment_id_fk"
    add_foreign_key "hearing_appeal_stream_snapshots", "legacy_appeals", column: "appeal_id", name: "hearing_appeal_stream_snapshots_appeal_id_fk"
    add_foreign_key "hearing_appeal_stream_snapshots", "legacy_hearings", column: "hearing_id", name: "hearing_appeal_stream_snapshots_hearing_id_fk"
    add_foreign_key "hearing_days", "users", column: "judge_id", name: "hearing_days_judge_id_fk"
    add_foreign_key "hearing_issue_notes", "hearings", name: "hearing_issue_notes_hearing_id_fk"
    add_foreign_key "hearing_issue_notes", "request_issues", name: "hearing_issue_notes_request_issue_id_fk"
    add_foreign_key "hearing_task_associations", "tasks", column: "hearing_task_id", name: "hearing_task_associations_hearing_task_id_fk"
    add_foreign_key "hearings", "hearing_days", name: "hearings_hearing_day_id_fk"
    add_foreign_key "hearings", "users", column: "judge_id", name: "hearings_judge_id_fk"
    add_foreign_key "ihp_drafts", "organizations", name: "ihp_drafts_organization_id_fk"
    add_foreign_key "job_notes", "users", name: "job_notes_user_id_fk"
    add_foreign_key "judge_case_reviews", "users", column: "attorney_id", name: "judge_case_reviews_attorney_id_fk"
    add_foreign_key "judge_case_reviews", "users", column: "judge_id", name: "judge_case_reviews_judge_id_fk"
    add_foreign_key "judge_case_reviews", "tasks", name: "judge_case_reviews_task_id_fk"
    add_foreign_key "legacy_hearings", "legacy_appeals", column: "appeal_id", name: "legacy_hearings_appeal_id_fk"
    add_foreign_key "legacy_issue_optins", "request_issues", name: "legacy_issue_optins_request_issue_id_fk"
    add_foreign_key "legacy_issues", "request_issues", name: "legacy_issues_request_issue_id_fk"
    add_foreign_key "messages", "users", name: "messages_user_id_fk"
    add_foreign_key "non_availabilities", "schedule_periods", name: "non_availabilities_schedule_period_id_fk"
    add_foreign_key "organizations_users", "organizations", name: "organizations_users_organization_id_fk"
    add_foreign_key "ramp_election_rollbacks", "ramp_elections", name: "ramp_election_rollbacks_ramp_election_id_fk"
    add_foreign_key "ramp_issues", "ramp_issues", column: "source_issue_id", name: "ramp_issues_source_issue_id_fk"
    add_foreign_key "remand_reasons", "decision_issues", name: "remand_reasons_decision_issue_id_fk"
    add_foreign_key "request_decision_issues", "decision_issues", name: "request_decision_issues_decision_issue_id_fk"
    add_foreign_key "request_decision_issues", "request_issues", name: "request_decision_issues_request_issue_id_fk"
    add_foreign_key "request_issues", "decision_issues", column: "contested_decision_issue_id", name: "request_issues_contested_decision_issue_id_fk"
    add_foreign_key "request_issues", "request_issues", column: "corrected_by_request_issue_id", name: "request_issues_corrected_by_request_issue_id_fk"
    add_foreign_key "request_issues", "end_product_establishments", name: "request_issues_end_product_establishment_id_fk"
    add_foreign_key "request_issues", "request_issues", column: "ineligible_due_to_id", name: "request_issues_ineligible_due_to_id_fk"
    add_foreign_key "sent_hearing_email_events", "users", column: "sent_by_id", name: "sent_hearing_email_events_sent_by_id_fk"
    add_foreign_key "special_issue_lists", "appeals", name: "special_issue_lists_appeal_id_fk"
    add_foreign_key "task_timers", "tasks", name: "task_timers_task_id_fk"
    add_foreign_key "tasks", "users", column: "assigned_by_id", name: "tasks_assigned_by_id_fk"
    add_foreign_key "tasks", "users", column: "cancelled_by_id", name: "tasks_cancelled_by_id_fk"
    add_foreign_key "tasks", "tasks", column: "parent_id", name: "tasks_parent_id_fk"
    add_foreign_key "transcriptions", "hearings", name: "transcriptions_hearing_id_fk"
    add_foreign_key "user_quotas", "team_quotas", name: "user_quotas_team_quota_id_fk"
    add_foreign_key "vbms_uploaded_documents", "appeals", name: "vbms_uploaded_documents_appeal_id_fk"
    add_foreign_key "virtual_hearing_establishments", "virtual_hearings", name: "virtual_hearing_establishments_virtual_hearing_id_fk"
    add_foreign_key "virtual_hearings", "users", column: "created_by_id", name: "virtual_hearings_created_by_id_fk"
    add_foreign_key "vso_configs", "organizations", name: "vso_configs_organization_id_fk"
  end
end
