class CreateBrieffReturnType < ActiveRecord::Migration[6.1]
  def up
    safety_assured do
      execute(
        <<-SQL
          CREATE TYPE brieff_record AS (
            bfkey TEXT,
            bfddec DATE,
            bfcorkey TEXT,
            bfcorlid TEXT,
            bfdcn TEXT,
            bfdocind TEXT,
            bfpdnum TEXT,
            bfdpdcn DATE,
            bforgtic TEXT,
            bfdorg DATE,
            bfdthurb DATE,
            bfdnod DATE,
            bfdsoc DATE,
            bfd19 DATE,
            bf41stat DATE,
            bfmstat TEXT,
            bfmpro TEXT,
            bfdmcon DATE,
            bfregoff TEXT,
            bfissnr TEXT,
            bfrdmref TEXT,
            bfcasev TEXT,
            bfcaseva TEXT,
            bfcasevb TEXT,
            bfcasevc TEXT,
            bfboard TEXT,
            bfbsasgn DATE,
            bfattid TEXT,
            bfdasgn DATE,
            bfcclkid TEXT,
            bfdqrsnt DATE,
            bfdlocin DATE,
            bfdloout DATE,
            bfstasgn TEXT,
            bfcurloc TEXT,
            bfnrcopy TEXT,
            bfmemid TEXT,
            bfdmem DATE,
            bfnrci TEXT,
            bfcallup TEXT,
            bfcallyymm TEXT,
            bfhines TEXT,
            bfdcfld1 TEXT,
            bfdcfld2 TEXT,
            bfdcfld3 TEXT,
            bfac TEXT,
            bfdc TEXT,
            bfha TEXT,
            bfic TEXT,
            bfio TEXT,
            bfms TEXT,
            bfoc TEXT,
            bfsh TEXT,
            bfso TEXT,
            bfhr TEXT,
            bfst TEXT,
            bfdrodec DATE,
            bfssoc1 DATE,
            bfssoc2 DATE,
            bfssoc3 DATE,
            bfssoc4 DATE,
            bfssoc5 DATE,
            bfdtb DATE,
            bftbind TEXT,
            bfdcue DATE,
            bfddvin DATE,
            bfddvout DATE,
            bfddvwrk DATE,
            bfddvdsp DATE,
            bfddvret DATE,
            bfddro DATE,
            bfdroid TEXT,
            bfdrortr TEXT,
            bfro1 TEXT,
            bflot TEXT,
            bfbox TEXT,
            bfdtbready DATE,
            bfarc TEXT,
            bfdarcin DATE,
            bfdarcout DATE,
            bfarcdisp TEXT,
            bfsub TEXT,
            bfrocdoc TEXT,
            bfdrocket DATE,
            bfdcertool DATE
          )
        SQL
      )
    end
  end

  def down
    safety_assured { execute("DROP TYPE brieff_record") }
  end
end
