export const ACTIONS = {
  FORMAT_LEVER_HISTORY: 'FORMAT_LEVER_HISTORY',
  UPDATE_AFFINITY_LEVER: 'UPDATE_AFFINITY_LEVER',
  UPDATE_LEVER_VALUE: 'UPDATE_LEVER_VALUE',
  SAVE_LEVERS: 'SAVE_LEVERS',
  REVERT_LEVERS: 'REVERT_LEVERS',
  SHOW_SUCCESS_BANNER: 'SHOW_SUCCESS_BANNER',
  HIDE_SUCCESS_BANNER: 'HIDE_SUCCESS_BANNER',
  LOAD_LEVERS: 'LOAD_LEVERS',
  INITIAL_LOAD: 'INITIAL_LOAD',
  UPDATE_LEVER: 'UPDATE_LEVER',
  SET_USER_IS_ACD_ADMIN: 'SET_USER_IS_ACD_ADMIN'
};
