export const ACTIONS = {
  ADD_LEVER_VALIDATION_ERRORS: 'ADD_LEVER_VALIDATION_ERRORS',
  UPDATE_RADIO_LEVER: 'UPDATE_RADIO_LEVER',
  UPDATE_COMBINATION_LEVER: 'UPDATE_COMBINATION_LEVER',
  UPDATE_BOOLEAN_LEVER: 'UPDATE_BOOLEAN_LEVER',
  UPDATE_TEXT_LEVER: 'UPDATE_TEXT_LEVER',
  UPDATE_NUMBER_LEVER: 'UPDATE_NUMBER_LEVER',
  SAVE_LEVERS: 'SAVE_LEVERS',
  REMOVE_LEVER_VALIDATION_ERRORS: 'REMOVE_LEVER_VALIDATION_ERRORS',
  RESET_ALL_VALIDATION_ERRORS: 'RESET_ALL_VALIDATION_ERRORS',
  HIDE_BANNER: 'HIDE_BANNER',
  LOAD_LEVERS: 'LOAD_LEVERS',
  LOAD_HISTORY: 'LOAD_HISTORY',
  SET_USER_IS_ACD_ADMIN: 'SET_USER_IS_ACD_ADMIN',
  VALIDATE_INPUT: 'VALIDATE_INPUT'
};
