export const ACTIONS = {
  FORMAT_LEVER_HISTORY: 'FORMAT_LEVER_HISTORY',
  UPDATE_RADIO_LEVER: 'UPDATE_RADIO_LEVER',
  UPDATE_COMBINATION_LEVER: 'UPDATE_COMBINATION_LEVER',
  UPDATE_BOOLEAN_LEVER: 'UPDATE_BOOLEAN_LEVER',
  UPDATE_TEXT_LEVER: 'UPDATE_TEXT_LEVER',
  UPDATE_NUMBER_LEVER: 'UPDATE_NUMBER_LEVER',
  SAVE_LEVERS: 'SAVE_LEVERS',
  REVERT_LEVERS: 'REVERT_LEVERS',
  HIDE_BANNER: 'HIDE_BANNER',
  LOAD_LEVERS: 'LOAD_LEVERS',
  INITIAL_LOAD: 'INITIAL_LOAD',
  UPDATE_LEVER: 'UPDATE_LEVER'
};
