export const ACTIONS = {
  FETCH_CAVC_DECISION_REASONS: 'FETCH_CAVC_DECISION_REASONS',
  FETCH_CAVC_SELECTION_BASES: 'FETCH_CAVC_SELECTION_BASES',
  FETCH_INITIAL_DASHBOARD_DATA: 'FETCH_INITIAL_DASHBOARD_DATA'
};
