export const ACTIONS = {
  FETCH_CAVC_DECISION_REASONS: 'FETCH_CAVC_DECISION_REASONS',
  FETCH_CAVC_SELECTION_BASES: 'FETCH_CAVC_SELECTION_BASES',
  FETCH_INITIAL_DASHBOARD_DATA: 'FETCH_INITIAL_DASHBOARD_DATA',
  UPDATE_DASHBOARD_ISSUES: 'UPDATE_DASHBOARD_ISSUES'
};

export const LABELS = {
  CAVC_DASHBOARD_ISSUES: 'Issues',
  CAVC_DASHBOARD_DISPOSITIONS: 'Dispositions',
  BOARD_DECISION_DATE: 'Board Decision Date',
  BOARD_DOCKET_NUMBER: 'Board Docket Number',
  CAVC_DECISION_DATE: 'CAVC Decision Date',
  CAVC_DOCKET_NUMBER: 'CAVC Docket Number',
  IS_JMR: 'Joint Motion for Remand?'
};
