export const ACTIONS = {
  FETCH_CAVC_DECISION_REASONS: 'FETCH_CAVC_DECISION_REASONS',
  FETCH_CAVC_SELECTION_BASES: 'FETCH_CAVC_SELECTION_BASES',
  FETCH_INITIAL_DASHBOARD_DATA: 'FETCH_INITIAL_DASHBOARD_DATA',
  RESET_DASHBOARD_DATA: 'RESET_DASHBOARD_DATA',
  SET_CHECKED_DECISION_REASONS: 'SET_CHECKED_DECISION_REASONS',
  SET_BASIS_FOR_REASON_CHECKBOX: 'SET_BASIS_FOR_REASON_CHECKBOX',
  SET_INITIAL_CHECKED_DECISION_REASONS: 'SET_INITIAL_CHECKED_DECISION_REASONS',
  REMOVE_CHECKED_DECISION_REASON: 'REMOVE_CHECKED_DECISION_REASON',
  UPDATE_DASHBOARD_ISSUES: 'UPDATE_DASHBOARD_ISSUES',
  REMOVE_DASHBOARD_ISSUE: 'REMOVE_DASHBOARD_ISSUE',
  UPDATE_DASHBOARD_DATA: 'UPDATE_DASHBOARD_DATA',
  SAVE_DASHBOARD_DATA_FAILURE: 'SAVE_DASHBOARD_DATA_FAILURE',
  SET_DISPOSITION_VALUE: 'SET_DISPOSITION_VALUE'
};

export const LABELS = {
  CAVC_DASHBOARD_ADDED_ISSUES: 'Added Issues',
  CAVC_DASHBOARD_ISSUES: 'Issues',
  CAVC_DASHBOARD_DISPOSITIONS: 'Dispositions',
  BOARD_DECISION_DATE: 'Board Decision Date',
  BOARD_DOCKET_NUMBER: 'Board Docket Number',
  CAVC_DECISION_DATE: 'CAVC Decision Date',
  CAVC_DOCKET_NUMBER: 'CAVC Docket Number',
  IS_JMR: 'Joint Motion for Remand?',
  ADD_ISSUE_DESCRIPTION: 'Issue Description',
  ADD_BASIS_BUTTON_LABEL: 'Add basis',
  REMOVE_BASIS_BUTTON_LABEL: 'Remove basis'
};

export const DECISION_REASON_LABELS = {
  DECISION_REASON_TITLE: 'Decision Reasons',
  DECISION_REASON_PROMPT: 'Select reasons why this issue\'s decision was changed',
  DECISION_REASON_BASIS_LABEL: 'Basis for this selection'
};

