#!/bin/sh

# Script that will be ran by husky as a pre-commit git hook.
#
# To be able to run the pre-commit script run:
#  chmod +x .husky/pre-commit

FILES=$(git diff --cached --name-only)
[ -z "$FILES" ] && exit 0

# Run lint-staged on all staged
echo "$FILES" | (cd $(git rev-parse --show-toplevel)/client; yarn lint-staged)
