CONNECT sys/Oradoc_db1@BVAP as sysdba

ALTER SESSION set "_ORACLE_SCRIPT"=true;

CREATE USER VACOLS IDENTIFIED BY VACOLS;
GRANT UNLIMITED TABLESPACE TO VACOLS;
GRANT CREATE SESSION TO VACOLS;

@/ORCL/vacols_copy_1_tablespaces.sql
@/ORCL/vacols_copy_2_tables.sql
