// actions
export const CHANGE_SPECIAL_ISSUE = 'CHANGE_SPECIAL_ISSUE';
export const CHANGE_ESTABLISH_CLAIM_FIELD = 'CHANGE_ESTABLISH_CLAIM_FIELD';
export const TOGGLE_CANCEL_TASK_MODAL = 'TOGGLE_CANCEL_TASK_MODAL';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';
export const CHANGE_CANCEL_FEEDBACK = 'CHANGE_CANCEL_FEEDBACK';
export const VALIDATE_CANCEL_FEEDBACK = 'VALIDATE_CANCEL_FEEDBACK';
export const REQUEST_CANCEL_FEEDBACK = 'REQUEST_CANCEL_FEEDBACK';
export const REQUEST_CANCEL_FEEDBACK_FAILURE = 'REQUEST_CANCEL_FEEDBACK_FAILURE';
export const INCREMENT_MODIFIER_ON_DUPLICATE_EP_ERROR = 'INCREMENT_MODIFIER_ON_DUPLICATE_EP_ERROR';

// constants
export const FULL_GRANT = 'Full Grant';
export const MODIFIER_OPTIONS = [
  '070',
  '071',
  '072',
  '073',
  '074',
  '075',
  '076',
  '077',
  '078',
  '079'
];

export const ARC_STATION_OF_JURISDICTION = '397';
