// actions
export const CHANGE_SPECIAL_ISSUE = 'CHANGE_SPECIAL_ISSUE';
export const SHOW_SPECIAL_ISSUE_ERROR = 'SHOW_SPECIAL_ISSUE_ERROR';
export const CLEAR_SPECIAL_ISSUE_ERROR = 'CLEAR_SPECIAL_ISSUE_ERROR';
export const CHANGE_ESTABLISH_CLAIM_FIELD = 'CHANGE_ESTABLISH_CLAIM_FIELD';
export const TOGGLE_CANCEL_TASK_MODAL = 'TOGGLE_CANCEL_TASK_MODAL';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';
export const CHANGE_CANCEL_FEEDBACK = 'CHANGE_CANCEL_FEEDBACK';
export const VALIDATE_CANCEL_FEEDBACK = 'VALIDATE_CANCEL_FEEDBACK';
export const REQUEST_CANCEL_FEEDBACK = 'REQUEST_CANCEL_FEEDBACK';
export const REQUEST_CANCEL_FEEDBACK_FAILURE = 'REQUEST_CANCEL_FEEDBACK_FAILURE';
export const INCREMENT_MODIFIER_ON_DUPLICATE_EP_ERROR = 'INCREMENT_MODIFIER_ON_DUPLICATE_EP_ERROR';
export const PERFORM_ESTABLISH_CLAIM_START = 'PERFORM_ESTABLISH_CLAIM_START';
export const PERFORM_ESTABLISH_CLAIM_SUCCESS = 'PERFORM_ESTABLISH_CLAIM_SUCCESS';
export const PERFORM_ESTABLISH_CLAIM_FAILURE = 'PERFORM_ESTABLISH_CLAIM_FAILURE';
export const SUBMIT_DECISION_PAGE = 'SUBMIT_DECISION_PAGE';
export const SUBMIT_DECISION_PAGE_SUCCESS = 'SUBMIT_DECISION_PAGE_SUCCESS';
export const SUBMIT_DECISION_PAGE_FAILURE = 'SUBMIT_DECISION_PAGE_FAILURE';

// constants
export const FULL_GRANT = 'Full Grant';
export const MODIFIER_OPTIONS = [
  '070',
  '071',
  '072',
  '073',
  '074',
  '075',
  '076',
  '077',
  '078',
  '079'
];

export const ARC_STATION_OF_JURISDICTION = '397';
