// actions
//
export const HANDLE_SERVER_ERROR = 'HANDLE_SERVER_ERROR';

export const POPULATE_DOCKETS = 'POPULATE_DOCKETS';

export const SET_REPNAME = 'SET_REPNAME';
export const SET_WITNESS = 'SET_WITNESS';

export const SET_NOTES = 'SET_NOTES';
export const SET_DISPOSITION = 'SET_DISPOSITION';
export const SET_HOLD_OPEN = 'SET_HOLD_OPEN';
export const SET_AOD = 'SET_AOD';
export const SET_ADD_ON = 'SET_ADD_ON';
export const SET_TRANSCRIPT_REQUESTED = 'SET_TRANSCRIPT_REQUESTED';

export const POPULATE_WORKSHEET = 'POPULATE_WORKSHEET';

// issues
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_REOPEN = 'SET_REOPEN';
export const SET_ALLOW = 'SET_ALLOW';
export const SET_DENY = 'SET_DENY';
export const SET_REMAND = 'SET_REMAND';
export const SET_DISMISS = 'SET_DISMISS';
export const SET_VHA = 'SET_VHA';
export const ADD_ISSUE = 'ADD_ISSUE';

export const SET_CONTENTIONS = 'SET_CONTENTIONS';
export const SET_MILITARY_SERVICE = 'SET_MILITARY_SERVICE';
export const SET_EVIDENCE = 'SET_EVIDENCE';
export const SET_COMMENTS_FOR_ATTORNEY = 'SET_COMMENTS_FOR_ATTORNEY';

export const TOGGLE_SAVING = 'TOGGLE_SAVING';
export const SET_SAVE_FAILED = 'SET_SAVE_FAILED';

export const SET_EDITED_FLAG_TO_FALSE = 'SET_EDITED_FLAG_TO_FALSE';
