// actions
//
export const HANDLE_SERVER_ERROR = 'HANDLE_SERVER_ERROR';

export const POPULATE_DOCKETS = 'POPULATE_DOCKETS';
export const UPDATE_DAILY_DOCKET_NOTES = 'UPDATE_DAILY_DOCKET_NOTES';
export const UPDATE_DAILY_DOCKET_ACTION = 'UPDATE_DAILY_DOCKET_ACTION';
export const UPDATE_DAILY_DOCKET_TRANSCRIPT = 'UPDATE_DAILY_DOCKET_TRANSCRIPT';

export const POPULATE_WORKSHEET = 'POPULATE_WORKSHEET';
