// actions
//
export const HANDLE_SERVER_ERROR = 'HANDLE_SERVER_ERROR';

export const POPULATE_DOCKETS = 'POPULATE_DOCKETS';

export const SET_REPNAME = 'SET_REPNAME';
export const SET_WITNESS = 'SET_WITNESS';

export const SET_NOTES = 'SET_NOTES';
export const SET_DISPOSITION = 'SET_DISPOSITION';
export const SET_HOLD_OPEN = 'SET_HOLD_OPEN';
export const SET_AOD = 'SET_AOD';
export const SET_ADD_ON = 'SET_ADD_ON';
export const SET_TRANSCRIPT_REQUESTED = 'SET_TRANSCRIPT_REQUESTED';

export const POPULATE_WORKSHEET = 'POPULATE_WORKSHEET';

// issues
export const SET_DESCRIPTIONS = 'SET_DESCRIPTIONS';

export const SET_CONTENTIONS = 'SET_CONTENTIONS';
export const SET_MILITARY_SERVICE = 'SET_MILITARY_SERVICE';
export const SET_EVIDENCE = 'SET_EVIDENCE';
export const SET_COMMENTS_FOR_ATTORNEY = 'SET_COMMENTS_FOR_ATTORNEY';
