// actions
export const SCROLL_TO_COMMENT = 'SCROLL_TO_COMMENT';
export const SET_UP_PAGE_DIMENSIONS = 'SET_UP_PAGE_DIMENSIONS';
export const SET_PDF_DOCUMENT = 'SET_PDF_DOCUMENT';
export const CLEAR_PDF_DOCUMENT = 'CLEAR_PDF_DOCUMENT';
export const SET_DOCUMENT_LOAD_ERROR = 'SET_DOCUMENT_LOAD_ERROR';
export const CLEAR_DOCUMENT_LOAD_ERROR = 'CLEAR_DOCUMENT_LOAD_ERROR';
