name: Branch Creation Alert
on:
  workflow_dispatch:
  create:

jobs:
  send_branch_alert:
    name: Send Branch Creation Alert
    runs-on: ubuntu-2-cores-latest

    if: ${{ (github.event.ref_type == 'branch') && (
        contains('refs/heads/uat', github.ref) ||
        contains('refs/heads/prodtest', github.ref) ||
        contains('refs/heads/release', github.ref)
      ) }}

    steps:
      - name: Testing
        run: echo ${{ github.ref }}
