name: Branch Creation Alert
on:
  workflow_dispatch:
  create:

jobs:
  send_branch_alert:
    name: Send Branch Creation Alert
    runs-on: ubuntu-2-cores-latest

    if: ${{ (github.event.ref_type == 'branch') && contains(github.ref, fromJson('["refs/heads/uat", "refs/heads/release", "refs/heads/prodtest"]'))

    steps:
      - name: Testing
        run: echo ${{ github.ref }}
