name: Branch Creation Alert
on:
  workflow_dispatch:
  create:

jobs:
  send_branch_alert:
    name: Send Branch Creation Alert
    runs-on: ubuntu-2-cores-latest

    if: ${{ (github.event.ref_type == 'branch') && (
        contains(github.ref, 'refs/heads/uat') ||
        contains(github.ref, 'refs/heads/prodtest') ||
        contains(github.ref, 'refs/heads/release')
      ) }}

    steps:
      - name: Testing
        run: echo ${{ github.ref }}
