name: PRs to main
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "jeremy.shields@va.gov"
          git config --local user.name "Jeremy Shields"
    - name: Merge main back to dev
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge -Xtheirs --no-ff main -m "Auto-merge main back to dev"
          git push
