export const ACTIONS = {
  SET_FEATURE_TOGGLES: 'SET_FEATURE_TOGGLES',
  SET_USER_ORGANIZATIONS: 'SET_USER_ORGANIZATIONS',
  SET_ORGANIZATION_MEMBERSHIP_REQUESTS: 'SET_ORGANIZATION_MEMBERSHIP_REQUESTS',
};
